### ISSUE TITLE
Support for both real-time and non-realtime UltraHFR

### ISSUE THREAD

**Issue by mdrejhon** [hzwer/arXiv2020-RIFE#101]
Hello,

Inventor of TestUFO / Founder of Blur Busters here.

We are [pioneers](https://blurbusters.com/category/area51-display-research) in UltraHFR experiments (true 240fps on true 240Hz displays, as well as we're working with laboratory true-1000Hz displays of the future that will display 1000fps content in real time).   

(Before anyone asks, yes, [researchers have shown 1000Hz has human visible benefits -- scientific citations here](https://blurbusters.com/1000hz-journey) -- and another research article, [Stroboscopic Effect of Finite Frame Rate Displays](https://blurbusters.com/stroboscopics).)

I have an [Ultra HFR FAQ: Real-time 240fps, 480fps and 1000fps on real-time 240Hz, 480Hz and 1000Hz displays](https://blurbusters.com/ultrahfr) which shows how to speed up Phantom Flex videos to real-time speeds, as well as other high speed camera footage (e.g. 240fps GoPro HERO8 videos).  However, these are low quality, and filming 4K 60fps to be interpolated to 4K 240fps on prototype 4K 240Hz displays look much better.

I'm researching RIFE for potential suitability.  

Is it possible that RIFE could be modified to use a series of multiple RTX 3090-league series (SLI configurations), to do real-time UltraHFR -- say converting 4K 120fps HFR camera to 4K 960fps HFR in real-time?   We have access to such prototype display technology, albiet the GPU technology is lagging slightly behind what custom-built laboratory displays can now do.

(P.S. Some of the precursors are already on the market. An E-Cinema projector, the Christie 4K digital projector, is already capable of 480Hz, albiet at only 1080p.)

**Comment by n00mkrad** [comment]
Multi-GPU is possible, this code supports it: https://github.com/HeylonNHP/RIFE-Colab

However, there is no license file and the author refuses to contribute to this official repo.
