### ISSUE TITLE
[自制]集成了RIFE的开源视频超分辨率及补帧软件

### ISSUE THREAD

**Issue by AaronFeng753** [hzwer/arXiv2020-RIFE#106]
您好, 我看了一下贵项目的readme, 上面的两个支持RIFE的软件都正在开发中或者闭源. 

我自己有一个维护了很久的视频超分辨率项目, https://github.com/AaronFeng753/Waifu2x-Extension-GUI, 近期集成了RIFE, 已经开始进行v3的公开测试, v3版中已经可以在超分辨率后自动进行补帧. 如果您有兴趣的话可以写进readme里, 项目开源免费.

**Comment by hzwer** [comment]
非常赞！
