### ISSUE TITLE
 Processing taking forever or not even working

### ISSUE THREAD

**Issue by niizam** [hzwer/arXiv2020-RIFE#107]
Stuck at 98%
it happened when I ran it on Google Colab 

>  input.mp4, 2520.0 frames in total, 29.97FPS to 59.94FPS
> The audio will be merged after interpolation process
>  78% 1970/2520.0 [03:39<01:00,  9.12it/s]Unhandled exception in thread started by <function build_read_buffer at 0x7f07934e1510>
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.6/dist-packages/skvideo/io/ffmpeg.py", line 271, in _read_frame_data
>     assert len(arr) == framesize
> AssertionError
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "inference_video.py", line 139, in build_read_buffer
>     for frame in videogen:
>   File "/usr/local/lib/python3.6/dist-packages/skvideo/io/io.py", line 253, in vreader
>     for frame in reader.nextFrame():
>   File "/usr/local/lib/python3.6/dist-packages/skvideo/io/ffmpeg.py", line 297, in nextFrame
>     yield self._readFrame()
>   File "/usr/local/lib/python3.6/dist-packages/skvideo/io/ffmpeg.py", line 281, in _readFrame
>     s = self._read_frame_data()
>   File "/usr/local/lib/python3.6/dist-packages/skvideo/io/ffmpeg.py", line 275, in _read_frame_data
>     raise RuntimeError("%s" % (err1,))
> RuntimeError
>  98% 2471/2520.0 [04:31<00:05,  9.50it/s]

**Comment by hzwer** [comment]
I add a exception handler. But it seems that this issue should be handled by ffmpeg or sk-video,
