### ISSUE TITLE
Missing key(s) in state_dict

### ISSUE THREAD

**Issue by gioolio** [hzwer/arXiv2020-RIFE#108]
From yesterday I'm receiving this message:

`File "inference_video.py", line 81, in <module>
    model.load_model(os.path.join(os.path.dirname(os.path.realpath(__file__)), 'train_log'), -1)
  File "/content/arXiv2020-RIFE/model/RIFE_HDv2.py", line 164, in load_model
    convert(torch.load('{}/flownet.pkl'.format(path), map_location=device)))
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 1052, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for IFNet:
	Missing key(s) in state_dict: `
	
The main problem is: `copying a param with shape torch.Size([8]) from checkpoint, the shape in current model is torch.Size([4])`.
Does anyone changed the shape of the model ?

**EDIT:**
on line 79 of inference_video.py I changed RIFE_HDv2 to `from model.RIFE_HD import Model` and it works as before.

**Comment by hzwer** [comment]
Hello, I updated the model to HDv2, so you need to download new zip of parameters to fit the new code.
