### ISSUE TITLE
What is ternary loss

### ISSUE THREAD

**Issue by AmemiyaYuko** [hzwer/arXiv2020-RIFE#109]
看到您在训练时候用了这个loss。我才疏学浅，没见过这个loss，看代码也没有看懂，相关资料也没找到，不知道有没有这个loss的解释？

**Comment by hzwer** [comment]
https://github.com/lliuz/ARFlow/blob/master/losses/loss_blocks.py

光流训练常用这个，以 census ternary + optical flow 能检索到一些文献
