### ISSUE TITLE
Image sequence and input

### ISSUE THREAD

**Issue by Michaelwhite34** [hzwer/arXiv2020-RIFE#11]
Thanks for adding the png output function. Can you make the output name to be consistent with ffmpeg ? i.e. 0000.png 0001.png ----- 7821.png.And then we can use ffmpeg to deal with image sequence.
         Adding image sequence input would also be great.

**Comment by hzwer** [comment]
'00000001.png -> 00003213.png' is this OK? I don't want to pre-calculate the number of digits.

**Comment by Michaelwhite34** [comment]
@hzwer Maybe you can set an input  a that represents the number digits

**Comment by hzwer** [comment]
> @hzwer Maybe you can set an input a that represents the number digits

If the default is 8 bits, can it be used by ffmpeg?

**Comment by Michaelwhite34** [comment]
@hzwer  Do you mean bitdepth ? All common bitdepth should be accepted by ffmpeg. ..Of course it will be better to manually set bitdepth.

**Comment by Michaelwhite34** [comment]
@hzwer ...Maybe you mean the way 00000001 to 00003213. Not sure about this,I never tested this way.

**Comment by Michaelwhite34** [comment]
@hzwer  I just tested 00 to 07 ,it worked.So most likely it should work for above situation.

**Comment by hzwer** [comment]
Now I set a default way 00000001 to 00003213 for video, you can have a try.

**Comment by Michaelwhite34** [comment]
@hzwer  Why is 3213 ???  It should be all image from 00000001 to 99999999.

**Comment by Michaelwhite34** [comment]
- - Also can you add image sequence input as video ?

**Comment by hzwer** [comment]
OK, I will support that. BTW, 3213 is just an example.

**Comment by Michaelwhite34** [comment]
> OK, I will support that. BTW, 3213 is just an example.

@hzwer .It will be best if the input image name is like 0000000 to xxxxxxx

**Comment by n00mkrad** [comment]
You can change the code like this to read an image sequence instead of a video:

`videoCapture = cv2.VideoCapture("{}/%08d.png".format(args.input),cv2.CAP_IMAGES)
success, frame = videoCapture.read()`

Add the argument `--input ` followed by a folder of frames with zero-padding to 8 digits.

**Comment by n00mkrad** [comment]
Sadly it's apparently no longer possible to use an image squence as input as `skvideo` does not seem to support this.

**Comment by hzwer** [comment]
Emmm, it seems that you really need this feature, I will consider writing an interface.

**Comment by Tsubajashi** [comment]
its a feature many people would use, so it would be a great addition :)

**Comment by hzwer** [comment]
Done. @Michaelwhite34 @Tsubajashi @n00mkrad
