### ISSUE TITLE
Nothing is generating.

### ISSUE THREAD

**Issue by ktakanov** [hzwer/arXiv2020-RIFE#110]
Hello, i'm trying to use RIFE using the d emo.mp4 and others video. 
The outputs show that no FPS is generated and no videos are present when we finalize the command:
 - python3 inference_video.py --exp=2 --video=sample.mp4 --montage --skip

Fri Feb 19 14:55:27 2021       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 450.36.06    Driver Version: 450.36.06    CUDA Version: 11.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Quadro M4000        On   | 00000000:00:05.0 Off |                  N/A |
| 46%   24C    P8    12W / 120W |      1MiB /  8126MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+
sample.mp4, 0.0 frames in total, 0.0FPS to 0.0FPS
Will not merge audio because using png, fps or skip flag!
135it [00:43,  3.19it/s]

My packages:

attrs==19.1.0
backcall==0.1.0
bleach==3.1.0
certifi==2020.12.5
chardet==4.0.0
cloudpickle==1.2.1
cycler==0.10.0
Cython==0.29.13
dataclasses==0.8
decorator==4.4.0
defusedxml==0.6.0
dtrx==8.0.2
entrypoints==0.3
filelock==3.0.12
future==0.17.1
gdown==3.12.2
idna==2.10
imageio==2.9.0
imageio-ffmpeg==0.4.3
ipykernel==5.1.1
ipython==7.7.0
ipython-genutils==0.2.0
ipywidgets==7.5.1
jedi==0.14.1
Jinja2==2.10.1
joblib==0.13.2
json5==0.8.5
jsonschema==3.0.2
jupyter==1.0.0
jupyter-client==5.3.1
jupyter-console==6.0.0
jupyter-core==4.5.0
jupyterlab==1.0.4
jupyterlab-server==1.0.0
kiwisolver==1.1.0
MarkupSafe==1.1.1
matplotlib==3.1.1
mistune==0.8.4
moviepy==1.0.3
nbconvert==5.5.0
nbformat==4.4.0
notebook==6.0.0
numpy==1.17.0
opencv-python==4.5.1.48
pandas==0.25.0
pandocfilters==1.4.2
parso==0.5.1
pexpect==4.7.0
pickleshare==0.7.5
Pillow==6.1.0
proglog==0.1.9
prometheus-client==0.7.1
prompt-toolkit==2.0.9
protobuf==3.9.1
ptyprocess==0.6.0
Pygments==2.4.2
pygobject==3.26.1
pyparsing==2.4.2
pyrsistent==0.15.4
PySocks==1.7.1
python-apt==1.6.4
python-dateutil==2.8.0
python-distutils-extra==2.39
pytz==2019.2
PyYAML==5.1.2
pyzmq==18.0.2
qtconsole==4.5.2
requests==2.25.1
scikit-learn==0.21.3
scipy==1.3.0
Send2Trash==1.5.0
six==1.12.0
sk-video==1.1.10
terminado==0.8.2
testpath==0.4.2
torch==1.7.1
torch-nightly==1.2.0.dev20190805
torchvision==0.4.0a0+d31eafa
tornado==6.0.3
tqdm==4.57.0
traitlets==4.3.2
typing==3.7.4
typing-extensions==3.7.4.3
urllib3==1.26.3
wcwidth==0.1.7
webencodings==0.5.1
widgetsnbextension==3.5.1

My system:

Distributor ID: Ubuntu
Description:    Ubuntu 18.04.2 LTS
Release:        18.04
Codename:       bionic

30 GB ram
Quadro M4000

From the paperspace, using pytorch library package.

**Comment by ktakanov** [comment]
I also tried with this video: https://www.youtube.com/watch?v=5G4-LjIdRL0

**Comment by ktakanov** [comment]
When tried this command:
- !python3 inference_video.py --exp=2 --video=cut.mp4


-----------------
Fri Feb 19 15:09:01 2021       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 450.36.06    Driver Version: 450.36.06    CUDA Version: 11.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Quadro M4000        On   | 00000000:00:05.0 Off |                  N/A |
| 46%   27C    P5    14W / 120W |      1MiB /  8126MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+
cut.mp4, 0.0 frames in total, 0.0FPS to 0.0FPS
The audio will be merged after interpolation process
59it [00:34,  1.70it/s]
ffmpeg version 3.4.8-0ubuntu0.2 Copyright (c) 2000-2020 the FFmpeg developers
  built with gcc 7 (Ubuntu 7.5.0-3ubuntu1~18.04)
  configuration: --prefix=/usr --extra-version=0ubuntu0.2 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --enable-gpl --disable-stripping --enable-avresample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librubberband --enable-librsvg --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-omx --enable-openal --enable-opengl --enable-sdl2 --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libopencv --enable-libx264 --enable-shared
  libavutil      55. 78.100 / 55. 78.100
  libavcodec     57.107.100 / 57.107.100
  libavformat    57. 83.100 / 57. 83.100
  libavdevice    57. 10.100 / 57. 10.100
  libavfilter     6.107.100 /  6.107.100
  libavresample   3.  7.  0 /  3.  7.  0
  libswscale      4.  8.100 /  4.  8.100
  libswresample   2.  9.100 /  2.  9.100
  libpostproc    54.  7.100 / 54.  7.100
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'cut.mp4':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2avc1mp41
    encoder         : Lavf57.83.100
  Duration: 00:00:02.02, start: 0.000000, bitrate: 3553 kb/s
    Stream #0:0(und): Video: h264 (High) (avc1 / 0x31637661), yuv420p, 1280x720 [SAR 1:1 DAR 16:9], 3464 kb/s, 30 fps, 30 tbr, 15360 tbn, 60 tbc (default)
    Metadata:
      handler_name    : VideoHandler
    Stream #0:1(eng): Audio: aac (LC) (mp4a / 0x6134706D), 44100 Hz, stereo, fltp, 116 kb/s (default)
    Metadata:
      handler_name    : SoundHandler
Output #0, matroska, to './temp/audio.mkv':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2avc1mp41
    encoder         : Lavf57.83.100
    Stream #0:0(eng): Audio: aac (LC) ([255][0][0][0] / 0x00FF), 44100 Hz, stereo, fltp, 116 kb/s (default)
    Metadata:
      handler_name    : SoundHandler
Stream mapping:
  Stream #0:1 -> #0:0 (copy)
Press [q] to stop, [?] for help
size=      30kB time=00:00:01.99 bitrate= 123.2kbits/s speed=1.29e+03x    
video:0kB audio:29kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 4.792583%
Audio transfer failed. Interpolated video will have no audio
Traceback (most recent call last):
  File "inference_video.py", line 232, in <module>
    transferAudio(args.video, vid_out_name)
  File "inference_video.py", line 34, in transferAudio
    os.rename(targetVideo, targetNoAudio)
FileNotFoundError: [Errno 2] No such file or directory: 'cut_4X_0fps.mp4' -> 'cut_4X_0fps_noaudio.mp4'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "inference_video.py", line 236, in <module>
    os.rename(targetNoAudio, vid_out_name)
FileNotFoundError: [Errno 2] No such file or directory: 'cut_4X_0fps_noaudio.mp4' -> 'cut_4X_0fps.mp4'

**Comment by ktakanov** [comment]
Please, which ffmpeg do I have to use?
My version:
ffmpeg version 3.4.8-0ubuntu0.2 Copyright (c) 2000-2020 the FFmpeg developers

**Comment by Tsubajashi** [comment]
try ffmpeg 4.3.2, 3.4.8 sounds pretty old to me

**Comment by ktakanov** [comment]
I think, can you put a fixed version in requirements.txt? This could help future issues.

**Comment by ktakanov** [comment]
Tried ffmpeg 4.x and not worked. 


Still not getting the right number of frames:

Mon Feb 22 15:41:47 2021       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 450.36.06    Driver Version: 450.36.06    CUDA Version: 11.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Quadro M4000        On   | 00000000:00:05.0 Off |                  N/A |
| 46%   29C    P8    11W / 120W |      1MiB /  8126MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+
demo.mp4, 0.0 frames in total, 0.0FPS to 0.0FPS
Will not merge audio because using png, fps or skip flag!
248it [00:48,  5.00it/s]Warning: Your video has 100 static frames, skipping them may change the duration of the generated video.
430it [01:32,  4.05it/s]


Please try using in paperspace enviroment

> try ffmpeg 4.3.2, 3.4.8 sounds pretty old to me

**Comment by ktakanov** [comment]
I finally got it. We need to use python3.8  I was using python3.6. I created a virtual environment and installed requirements.txt
