### ISSUE TITLE
problem when installing rife 

### ISSUE THREAD

**Issue by FKOV** [hzwer/arXiv2020-RIFE#117]
Hi, every time i try to git colne the repository it gives me the following error 

git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

Can anyone help? thank y all for your precious time and i have to say to the developer/developers of this porject that they did an amazing work as i saw the samples

**Comment by richardletshacks** [comment]
try ``git clone https://github.com/hzwer/arXiv2020-RIFE`` instead

**Comment by FKOV** [comment]
This worked, thanks mate
