### ISSUE TITLE
Add argument to keep sound ?

### ISSUE THREAD

**Issue by Tempetek** [hzwer/arXiv2020-RIFE#12]
Sorry if I am overstepping the bounds of the project, but I have found that the interpolated output has no sounds. It would be awesome if you could add an argument (like --sounds) to keep the sound on the generated output -- or at least when output is the same length as input.

EDIT: Temporary solution:
ffmpeg -i "$video_name" audio.mp3 -y
ffmpeg -i "video_4x.mp4" -i "audio.mp3" -map 0:0 -map 1:0 -c:v copy -c:a copy "video_4x_audio.mp4" -y

**Comment by hzwer** [comment]
I intend to support it. I need to learn some ffmpeg and perform a lot of tests. It takes a few days.

**Comment by Michaelwhite34** [comment]
@Tempetek  Hi,you can check out lossless cut on github.It can seperate or merge different tracks in a video without re-encoding in a super-fast way.

**Comment by SleepingFox88** [comment]
https://superuser.com/questions/277642/how-to-merge-audio-and-video-file-in-ffmpeg#277667
This article discusses multiple ways of combining an audio file and a video file into one.

I personally found ``ffmpeg -i video.mp4 -i audio.wav -c:v copy -c:a aac output.mp4`` to execute at x58 playback speed, and ``ffmpeg -i video.mp4 -i audio.wav -c copy output.mkv`` to execute at x126 playback speed. both are acceptably fast, though it looks like we will get speed gains if we are willing to export to .mkv instead of .mp4

I just tested and LosslessCut does indeed provide a GUI tool for instantly ripping the sound from a video. I have not looked into using that via CLI yet.

**Comment by SleepingFox88** [comment]
@hzwer If this was fixed, there was no documentation created for telling users how to use it.

**Comment by SleepingFox88** [comment]
```python
# import dependancies
if True:
    import moviepy.editor
    import os
    import shutil

# main program
if True:

    # declare constants
    if True:
        originalVideoFile = "./video.mp4"
        audiolessVideoFile = "./video_2X_48fps.mp4"
        tempAudioFileName = "./temp/audio.mp3"

    # split audio from original video file and store in "temp" directory
    if True:

        # extract audio from video
        if True:
            video = moviepy.editor.VideoFileClip(originalVideoFile)
            audio = video.audio

        # clear old "temp" directory if it exits
        if os.path.isdir("temp"):
            # remove temp directory
            shutil.rmtree("temp")

        # create new "temp" directory
        os.makedirs("temp")

        # write audio file to "temp" directory
        audio.write_audiofile(tempAudioFileName)

    # combine audio file and new video file
    os.system("ffmpeg -y -i " + audiolessVideoFile + " -i " + tempAudioFileName + " -c copy output.mkv")

    # remove temp directory
    shutil.rmtree("temp")
```

In case this hasn't already been fixed, here is an example script I made showing how to transfer audio from the original video to the new video. Assuming you have both file names.

I am happy to make a pull request containing this fix but I have yet to identify where this should go in ``inference_video.py``

### Notes:

Audio extraction in this script is not instant like in [losslessCut](https://github.com/mifi/lossless-cut) but it works. Instant lossless audio stripping could be an optimization for the future.

Per issue #28 the video/audio synchronization in these videos might be off by a tiny amount but it's in sync enough to implement audio for now.
