### ISSUE TITLE
Scale 0.5 at 4K looks noticably worse than rife-ncnn-vulkan's UHD mode

### ISSUE THREAD

**Issue by n00mkrad** [hzwer/arXiv2020-RIFE#122]
Setting the scale to 0.5 for 4K content doesn't seem to improve results over 1.0, and looks worse than the UHD mode in RIFE-NCNN.

![ncnn-uhd-vs-scale0 5](https://user-images.githubusercontent.com/61149547/109423371-68ed9280-79df-11eb-9c80-42b312d72dc6.gif)

**Comment by hzwer** [comment]
Revert to last version, should be consistent with UHD mode.
