### ISSUE TITLE
这个算法能否在Vapoursynth，Avisynth+等帧服务器上实现

### ISSUE THREAD

**Issue by ccicnce113424** [hzwer/arXiv2020-RIFE#123]
这样的话如果处理速度够快的话可以实时播放。帧服务器也利于压制。处理过程不需要占用大量硬盘空间

**Comment by AstomMars** [comment]
万人血书求实现（2/10000）

**Comment by ccicnce113424** [comment]
> 万人血书求实现（2/10000）

https://github.com/nihui/rife-ncnn-vulkan/issues/11

可以到这里来求，我不希望请求换来一个只支持N卡的东西

**Comment by YiWeiHuang-stack** [comment]
这个我觉得不能实现，但支持A卡就有点困难了，因为A卡用rife-ncnn-vulkan跑效率太低了

**Comment by YiWeiHuang-stack** [comment]
> 这样的话如果处理速度够快的话可以实时播放。帧服务器也利于压制。处理过程不需要占用大量硬盘空间
源码本来就不需要占用硬盘空间

**Comment by ccicnce113424** [comment]
> 这个我觉得不难实现，但支持A卡就有点困难了，因为A卡用rife-ncnn-vulkan跑效率太低了

ncnn实现与这个实现的性能差距有多大

**Comment by ccicnce113424** [comment]
> > 这样的话如果处理速度够快的话可以实时播放。帧服务器也利于压制。处理过程不需要占用大量硬盘空间
> 
> 源码本来就不需要占用多少硬盘空间，而且你可以用ffmpeg和python的管道读写视频帧

1.占空间大的是视频拆出来的帧
2.用帧服务器可以进行其他处理，不需要在处理过程中对画面进行多次编码降低效率。比如我计划将这个和Anime4KCPP配合使用以提示2d动画的观感。

**Comment by YiWeiHuang-stack** [comment]
代码你自己写呗😂

**Comment by ccicnce113424** [comment]
> Anime4KCPP还是算了，效果不太行，会糊画面，多半都是负优化，我记得他的版本停留在0.9

有替代方案吗？

**Comment by YiWeiHuang-stack** [comment]
如果一定要追求和anime4K同样的速度，那没有替代方案，但是想速度和质量均衡的话，realsr和waifu2x是不错的

**Comment by ccicnce113424** [comment]
> 如果一定要追求和anime4K同样的速度，那没有替代方案，但是想速度和质量均衡的话，realsr和waifu2x是不错的

1.RealSR好像偏向于真实图片处理，适合处理2d动漫吗
2.RealSR和Waifu2x性能相比如何
3.Anime4KCPP内置的ACNET算法如何
4.各个算法的ncnn实现和pytorch实现性能差距有多大

**Comment by YiWeiHuang-stack** [comment]
RealSR对图片的还原性比较强，我尝试把图片缩小四倍之后用realsr超回来，比waifu2x清晰
waifu2x速度比realsr快很多，而且降噪能力很强
Anime4KCPP的ACNET我试过了，仅放大还可以，但是优化画面质量的能力不强
同样环境下，用2080S卡分别跑ncnn和torch实现的RIFE 我测出来，ncnn比torch慢三倍左右，因为我手里没有A卡，所以没对A卡进行测试

**Comment by ccicnce113424** [comment]
感谢回答
这个算法和dain，cain比较起来如何

**Comment by YiWeiHuang-stack** [comment]
RIFE v2.4补出来，我觉得大多数场景都比DAIN补的好，速度实测有DAIN的20倍以上，CAIN我就不说了，我之前训练过300轮，实测效果不佳，运动幅度大一点点就会出现棋盘格，且会出现消失与模糊

**Comment by YiWeiHuang-stack** [comment]
QQ群:264023742 我们这里有一些补帧超分爱好者，可以一起讨论

**Comment by ccicnce113424** [comment]
目前能在帧服务器中能使用的插帧工具只有算法老旧的mvtools，至于超分……就只有Anime4KCPP和Waifu2X（第三方）有适配

**Comment by HolyWu** [comment]
https://github.com/HomeOfVapourSynthEvolution/VapourSynth-RIFE-ncnn-Vulkan
