### ISSUE TITLE
关于数据集

### ISSUE THREAD

**Issue by PureMmm** [hzwer/arXiv2020-RIFE#125]
你好，我看到你使用的liteflow制作的光流groudtruth，然后和把vimeo的三帧连续图（im1，im2，im3）拼接到一起生成npz文件。是这样做的吗？因为我自己尝试制作光流后发现输出的光流效果不好（边界比较模糊）。我想请问一下可以通过网盘分享一下制作好的数据集吗？或者分享一下制作数据集的代码及与预训练的光流model。非常感谢。

**Comment by hzwer** [comment]
https://github.com/hzwer/arXiv2020-RIFE/issues/99, https://github.com/hzwer/arXiv2020-RIFE/issues/114
这个问题解释过了，这些代码我之后会放，我的意思是这个不太影响最后模型结果
