### ISSUE TITLE
RIFE interpolated video drops in quality

### ISSUE THREAD

**Issue by ItsLuk** [hzwer/arXiv2020-RIFE#127]
First of all, i would like to say that i am very amazed by RIFE, and what it can do. Now that we have that out of the way we come to the "issue", when i inerpolate videos the output loses quality. The video is slightly pixelated or i dont know, i think  you call it "artifact is added". I don't know if it's my hardware, RIFE or ffmpeg, but i just wanted to point it out to you. Maybe there are some settings im just missing.

**Comment by hzwer** [comment]
Most of these problems come from video encoding and decoding. In theory, the image should remain unchanged for the original frame. I think input and output from png will be better.  I recommend you to use GUI software like flow frames or RIFEAPP, I think they can deal with videos well.

**Comment by ItsLuk** [comment]
Okay, thank you very much :) appreciate your work.
