### ISSUE TITLE
frame blending instead of interpolation

### ISSUE THREAD

**Issue by deama** [hzwer/arXiv2020-RIFE#131]
So when I use this cmd implementation, it likes to mostly blend the frames instead of interpolating them, however if you use the software implementations, like flowframes, it interpolates it all. Here are some examples:

![new](https://user-images.githubusercontent.com/13488213/111068910-90a22780-84c2-11eb-81b3-d5e1a65d16b9.png)
![old](https://user-images.githubusercontent.com/13488213/111068918-94ce4500-84c2-11eb-9b2b-84ef062721e3.png)

It's supposed to be the weird blobby one, not the darker one.

**Comment by Tsubajashi** [comment]
"blending" appears if there is a scene change detected as far as i know - can you show the settings of flowframes for that matter?

**Comment by deama** [comment]
> "blending" appears if there is a scene change detected as far as i know - can you show the settings of flowframes for that matter?

The blending happens on the non-flowframe version, this version on this repository. Can this be disabled?
How do you want to see the settings on flowframes? Is there an export or something?

**Comment by deama** [comment]
Ah ok, I figured it out, simply remove this code or comment it out

`    if ssim < 0.5:
        print("TRIGGERED")
        output = []
        step = 1 / (2 ** args.exp)
        alpha = 0
        for i in range((2 ** args.exp) - 1):
            alpha += step
            beta = 1-alpha
            output.append(torch.from_numpy(np.transpose((cv2.addWeighted(frame[:, :, ::-1], alpha, lastframe[:, :, ::-1], beta, 0)[:, :, ::-1].copy()), (2,0,1))).to(device, non_blocking=True).unsqueeze(0).float() / 255.)`

**Comment by n00mkrad** [comment]
Flowframes has scene blending now as well.
