### ISSUE TITLE
No module named 'skyvideo' error

### ISSUE THREAD

**Issue by NerfPhaselock** [hzwer/arXiv2020-RIFE#134]
I followed the tutorial and got all the way to the point where I was going to test the demo video and I got an error that reads:
(RIFE) C:\Users\User\Desktop\RIFE>python inference_video.py --exp=2 --video=demo.mp4
Traceback (most recent call last):
  File "inference_video.py", line 10, in <module>
    import skvideo.io
ModuleNotFoundError: No module named 'skvideo'

I'm not sure what this means or how to fix it. Please forgive me as I am not very familiar with Python.

**Comment by TheDefinitionist** [comment]
Have the same issue but on Google Colab.

**Comment by lukbieli** [comment]
in my case helped to install sk-video by: pip install sk-video
