### ISSUE TITLE
Add frame blending option ontop of the interpolated frames?

### ISSUE THREAD

**Issue by deama** [hzwer/arXiv2020-RIFE#137]
Could a feature be added wherein the next frame is put ontop of the interpolated frame, like there's an afterimage of the next frame?

**Comment by deama** [comment]
Ok so I started to play around and managed to add my own modification to it to give it an afterimage effect.
at around line 220, or where it says "**output = make_inference(I0, I1, args.exp)**"
right after that line, put in:
`        carry = output
        output = []
        alpha = 0.2
        beta = 1-alpha
        for mid in carry:
            mid = (((mid[0] * 255.).byte().cpu().numpy().transpose(1, 2, 0)))
            nextFrame = mid[:h, :w]
            output.append(torch.from_numpy(np.transpose((cv2.addWeighted(frame[:, :, ::-1], alpha, nextFrame[:, :, ::-1], beta, 0)[:, :, ::-1].copy()), (2,0,1))).to(device, non_blocking=True).unsqueeze(0).float() / 255.)`

**Comment by n00mkrad** [comment]
Don't really see the point - Why interpolate something and then hide the interpolated frames under blended frames?

**Comment by deama** [comment]
> Don't really see the point - Why interpolate something and then hide the interpolated frames under blended frames?

It doesn't hide it, it creates a type of slight afterimage, so the interpolated frame is still there, it's just slightly transparent, and you can also see a bit of the next frame, I noticed this helps with noticing interpolated frames when watching snappy movements, like with anime. Sometimes I notice thin lines becoming spazzy when they get interpolated, this helps with that also.

**Comment by BakaBTZ** [comment]
Hey there great addition. I'am pretty new to coding in general, would you mind ant tell me where in which file I have to change the code snipet?

**Comment by BakaBTZ** [comment]
> Ok so I started to play around and managed to add my own modification to it to give it an afterimage effect.
> at around line 220, or where it says "**output = make_inference(I0, I1, args.exp)**"
> right after that line, put in:
> 
> > 
> 
> ```
>     carry = output
>     output = []
>     alpha = 0.2
>     beta = 1-alpha
>     for mid in carry:
>         mid = (((mid[0] * 255.).byte().cpu().numpy().transpose(1, 2, 0)))
>         nextFrame = mid[:h, :w]
>         output.append(torch.from_numpy(np.transpose((cv2.addWeighted(frame[:, :, ::-1], alpha, nextFrame[:, :, ::-1], beta, 0)[:, :, ::-1].copy()), (2,0,1))).to(device, non_blocking=True).unsqueeze(0).float() / 255.)
> ```
> 
> you can adjust the alpha value to tweak the transparency of the interpolation, higher values makes the interpolation less visible, but makes the afterimage more visible.
> I've done some tests and this should make the interpolation less spazy when it comes to certain choppy scenes (anime).

Hey there great addition. I'am pretty new to coding in general, would you mind ant tell me where in which file I have to change the code ?

**Comment by deama** [comment]
> > Ok so I started to play around and managed to add my own modification to it to give it an afterimage effect.
> > at around line 220, or where it says "**output = make_inference(I0, I1, args.exp)**"
> > right after that line, put in:
> > > 
> > 
> > 
> > ```
> >     carry = output
> >     output = []
> >     alpha = 0.2
> >     beta = 1-alpha
> >     for mid in carry:
> >         mid = (((mid[0] * 255.).byte().cpu().numpy().transpose(1, 2, 0)))
> >         nextFrame = mid[:h, :w]
> >         output.append(torch.from_numpy(np.transpose((cv2.addWeighted(frame[:, :, ::-1], alpha, nextFrame[:, :, ::-1], beta, 0)[:, :, ::-1].copy()), (2,0,1))).to(device, non_blocking=True).unsqueeze(0).float() / 255.)
> > ```
> > 
> > 
> > you can adjust the alpha value to tweak the transparency of the interpolation, higher values makes the interpolation less visible, but makes the afterimage more visible.
> > I've done some tests and this should make the interpolation less spazy when it comes to certain choppy scenes (anime).
> 
> Hey there great addition. I'am pretty new to coding in general, would you mind and tell me where in which file I have to change the code ?

inference_video.py

**Comment by hzwer** [comment]
#207 I think we implemented a proper processing method.
