### ISSUE TITLE
关于完整训练集

### ISSUE THREAD

**Issue by Someone-LikeU** [hzwer/arXiv2020-RIFE#139]
（看了一些issues里作者的评论，是国人，就用中文了）作者您好，我按照您说的方法把完整的Vimeo90K里每个triple的ft0.flo和ft1.flo都生成了一遍，我想完整的训练一次网络，请问这样的话train.py里要修改哪些地方？（我能使用的设备只有单机单卡，无法分布式）

**Comment by hzwer** [comment]
python3 -m torch.distributed.launch --nproc_per_node=4 train.py --world_size=4
把这句话两个 4 都改成 1 应该能跑
学习率可能调小一点（因为卡少 batchsize 小了）

**Comment by Someone-LikeU** [comment]
这个我在上周尝试的时候发现了。更具体的，我想问下作者用完整数据集来训练的时候，
也是像那100个sample一样，都先把每个triple和对应的.flo加工成(9*256*448)和(4*256*448)，
再压缩成一个.npz文件的吗？




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "hzwer/arXiv2020-RIFE"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年4月9日(星期五) 中午1:08
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [hzwer/arXiv2020-RIFE] 关于完整训练集 (#139)





 
python3 -m torch.distributed.launch --nproc_per_node=4 train.py --world_size=4
 把这句话两个 4 都改成 1 应该能跑
 学习率可能调小一点（因为卡少 batchsize 小了）

**Comment by hzwer** [comment]
我自己其实是没有这些步骤的，我们有分布式的数据存储系统，每个样本都是实时从云端读的；不一定要按我给的格式，总之dataloader能吐出正确训练样本即可

**Comment by Someone-LikeU** [comment]
好的，明白了，我仔细研究研究train.py。谢谢你。
