### ISSUE TITLE
关于新添加的VGG模型

### ISSUE THREAD

**Issue by 98mxr** [hzwer/arXiv2020-RIFE#142]
您好h佬，最近在试图训练RIFE时，发现RIFE更新了新的VGG损失函数相关代码，但在rife.py中相关代码被注释掉了。单纯的取消注释并修改相关代码后并不能顺利运行，想请问这部分工作是否是完成的。不胜感激。

就像这样
```
self.vgg = VGGPerceptualLoss().to(device)

# loss_G = loss_l1 + loss_cons + loss_ter
loss_G = self.vgg(pred, gt) + loss_cons + loss_ter
```

When trying to train RIFE recently, I found that RIFE updated the new VGG loss function related code, but the related code in rife.py was commented out. Simply uncomment and modify the relevant code can not start train, I would like to ask whether this part of the work is completed. I am very grateful.

like,this
```
self.vgg = VGGPerceptualLoss().to(device)

# loss_G = loss_l1 + loss_cons + loss_ter
loss_G = self.vgg(pred, gt) + loss_cons + loss_ter
```

**Comment by hzwer** [comment]
请问报错信息是什么呢？我应该测试过相关代码

**Comment by dcrmg** [comment]
在[loss.py第102行](https://github.com/hzwer/arXiv2020-RIFE/blob/1dc514b65021b813fd98acd1b36c3eaad1194440/model/loss.py#L102)报错
`NameError: name 'models' is not defined`
加引用
`import torchvision.models as models`
应该就可以了
