### ISSUE TITLE
Releasing RIFE as a pypi library with a CLI/API?

### ISSUE THREAD

**Issue by xhlulu** [hzwer/arXiv2020-RIFE#144]
I wonder if it'd be possible to publish this as a library that can be used as a command-line tool and/or an API?

I created a [fork of this repo](https://github.com/xhlulu/rife) and experimented with `setuptools` and some refactoring. Overall the fork seems to work fine when it's used in the following way:

> To install this library:
> ```
> pip install git+https://github.com/xhlulu/rife
> ```
> 
> To use RIFE inside Python:
> 
> ```python
> import rife
> model = rife.RIFE_HDv2.Model()
> ```
> To use the command line interfaces:
> ```bash
> rife-video --help  # Corresponds to inference_video.py
> rife-img --help  # Corresponds to inference_img.py
> ```
> The CLI can be used just like the `inference_video.py` and `inference_img.py` scripts. The following is adapted from the original readme:
> ```bash
> # You can use our demo video or your own video.
> rife-video --exp=1 --video=video.mp4 
> # (generate video_2X_xxfps.mp4)
> rife-video --exp=2 --video=video.mp4
> # (for 4X interpolation)
> rife-video --exp=1 --video=video.mp4 --scale=0.5
> # Image Interpolation
> rife-img --img img0.png img1.png --exp=4
> ```

Since there's some significant refactoring (though no actual change to the code behavior, mostly just restructuring/changing the imports), I'm not sure if it would be a good PR; @hzwer  what do you think?

**Comment by hzwer** [comment]
I think this project is mainly for developers, and ordinary users are recommended to use the GUI, so the pip package is not necessary.
