### ISSUE TITLE
关于训练时数据增强的问题

### ISSUE THREAD

**Issue by BoyuanJiang** [hzwer/arXiv2020-RIFE#146]
作者你好，我看到在你的dataset.py的[第68行](https://github.com/hzwer/arXiv2020-RIFE/blob/main/dataset.py#L68)有一个return，是不是意味着训练的时候其实没有对数据做反转等增强操作？

**Comment by hzwer** [comment]
不好意思，我在生成训练sample时误加了这行，已删除

**Comment by BoyuanJiang** [comment]
感谢回复，还有一个问题，请问你提供的最新的RIFEv2模型也是只用了Vimeo90K的训练集训练的吗？如果是的话训练的超参数也是batch size为64，初识学习率3e-4，一共训练300个epoch吗？

**Comment by hzwer** [comment]
你说的是 HDv2 吧
是用 vimeo90K 训练的，但是为了刷视觉效果，用了 1000 epoch，并且加了很强的数据增广

**Comment by BoyuanJiang** [comment]
对，方便具体说下用了什么数据增广的方式吗？以及有没有使用vgg loss呢？因为我自己尝试用 vimeo90K训练了一版HDv2，使用的是你提供的默认配置以及数据增广，在一些视频上的视觉效果跟你提供的预训练比差了一些。

**Comment by hzwer** [comment]
主要是 resize 增广（把训练数据放大 1.5x 2x 4x)，光流也对应放缩，以及用 vgg loss 替代 l1 loss
其它增广好像没什么效果

**Comment by BoyuanJiang** [comment]
感谢，我试一下你说的这几个点

**Comment by dcrmg** [comment]
and also 第64到67行也需要移除~~

**Comment by hzwer** [comment]
> and also 第64到67行也需要移除~~

Thanks.

**Comment by dcrmg** [comment]
请教一下对尝试使用不同光流网络做"overpowered teacher"有什么建议吗？比如LiteFlowNet3或RAFT。
也看到在[#99](https://github.com/hzwer/arXiv2020-RIFE/issues/99) [#114](https://github.com/hzwer/arXiv2020-RIFE/issues/114) 中讨论过指导光流性能提升对最终插帧性能的提升效果有限。
如果没有预期效果上的提升，不确定跟loss_cons的权重0.01有关么？按道理光流跟最后的效果应该是正相关的。试了一下RAFT，比原LiteFlowNet的效果是要稳健一些

**Comment by hzwer** [comment]
权重是为了使得各个 loss 的尺度类似，没有细致调过
能大概说一下最后收敛结果吗？如果能得到比目前 paper 更好的结果，我非常有兴趣再做一些实验

**Comment by dcrmg** [comment]
我表达的歧义了，是说单看光流的效果会好一些，最后的结果还没有训练出来，好的话PO出来

**Comment by BoyuanJiang** [comment]
> 主要是 resize 增广（把训练图放大 1.5x 2x 4x)，光流也对应放缩，以及用 vgg loss 替代 l1 loss
> 其它增广好像没什么效果

请问你这边提到的训练图放大4倍训练，对应的光流使用4x的训练图送到光流网络提取还是使用原始大小提取的光流然后直接放大4倍呢？

**Comment by hzwer** [comment]
@BoyuanJiang 
我只试过使用原始大小提取的光流然后直接放大4倍，因为这个模型只是为了给网友们玩的，所以实验没有做的很精细

**Comment by splinter21** [comment]
> 你说的是 HDv2 吧
> 是用 vimeo90K 训练的，但是为了刷视觉效果，用了 1000 epoch，并且加了很强的数据增广

为了刷视觉效果的意思是，实际上PSNR和SSIM是没有保障的吗（我支持使用别评价指标而不是PSNR和SSIM）

**Comment by hzwer** [comment]
> > 你说的是 HDv2 吧
> > 是用 vimeo90K 训练的，但是为了刷视觉效果，用了 1000 epoch，并且加了很强的数据增广
> 
> 为了刷视觉效果的意思是，实际上PSNR和SSIM是没有保障的吗（我支持使用别评价指标而不是PSNR和SSIM）

对的 我主要是对着几个hardcase调的模型
如果你想有指标可以用lpips

**Comment by dawei03896** [comment]
@hzwer 关于”我只试过使用原始大小提取的光流然后直接放大4倍，因为这个模型只是为了给网友们玩的，所以实验没有做的很精细“，是在IFNet后面的步骤将光流和原图直接放大到需要的倍数吗（包括GT）？
