### ISSUE TITLE
数据扩充

### ISSUE THREAD

**Issue by chiny92** [hzwer/arXiv2020-RIFE#150]
在RIFE代码训练中，我在哪里可以找到用于数据扩充和水平/垂直翻转的代码

似乎该论文在以下方面提到了这一点：

训练数据集。我们使用Vimeo90K数据集[37]
训练我们的模型。 Vimeo90K数据集包含51,312个三胞胎
用于训练，每个三联体包含三个连续的
分辨率为256448的视频帧。我们随机
通过水平和垂直翻转来扩充训练数据
训练过程中的时间和时间顺序颠倒。

**Comment by hzwer** [comment]
https://github.com/hzwer/arXiv2020-RIFE/blob/adc1957ef8214a541ce5feceaf8f4041bbc88c46/dataset.py#L64
