### ISSUE TITLE
关于训练rife-large的epochs疑问

### ISSUE THREAD

**Issue by JasonSheng-atp** [hzwer/arXiv2020-RIFE#153]
作者你好，我在训练large版本时用了150个epochs，发现loss只在开始50epochs内下降比较明显，测试后发现psnr和论文相差了1左右，想请教一下合适的训练epochs数目。
能否提供一下large的权重用于测试，因为之前看到好像有，忘记下载了。
感谢

**Comment by JasonSheng-atp** [comment]
loss的波动非常大

**Comment by rsjjdesj** [comment]
> 作者你好，我在训练large版本时用了150个epochs，发现loss只在开始50epochs内下降比较明显，测试后发现psnr和论文相差了1左右，想请教一下合适的训练epochs数目。
> 能否提供一下large的权重用于测试，因为之前看到好像有，忘记下载了。
> 感谢

您是否使用过数据集？或论文中给定的那个。我尝试使用我的数据集，并得到与您相同的观察结果：损失波动非常大。

**Comment by JasonSheng-atp** [comment]
> > 作者你好，我在训练large版本时用了150个epochs，发现loss只在开始50epochs内下降比较明显，测试后发现psnr和论文相差了1左右，想请教一下合适的训练epochs数目。
> > 能否提供一下large的权重用于测试，因为之前看到好像有，忘记下载了。
> > 感谢
> 
> 您是否使用过数据集？或论文中给定的那个。我尝试使用我的数据集，并得到与您相同的观察结果：损失波动非常大。

是的，我用的是vimeo90K

**Comment by hzwer** [comment]
你好，我用的 epoch 也是 300，但在 150 个 epoch 时已经能达到非常接近的性能。
如果出现不收敛的情况可以把 learning rate 适当调小一点。求问 RIFE base 版的性能你复现了吗？
我上传了一个训练好的权重：https://drive.google.com/file/d/1khrpNkbrACYk3YVfHuRDJS5iUDSN7vFw/view?usp=sharing

**Comment by JasonSheng-atp** [comment]
> 你好，我用的 epoch 也是 300，但在 150 个 epoch 时已经能达到非常接近的性能，如果出现不收敛的情况可以把 learning rate 适当调小一点。
> 求问 RIFE base 版的性能你复现了吗？
> 我上传了一个训练好的 RIFE-Large 权重：https://drive.google.com/file/d/1khrpNkbrACYk3YVfHuRDJS5iUDSN7vFw/view?usp=sharing

我正在训练base版的rife，排查一下我的问题，感谢你的回复
