### ISSUE TITLE
建筑场景插帧的bad case

### ISSUE THREAD

**Issue by BoyuanJiang** [hzwer/arXiv2020-RIFE#154]
作者你好，我尝试使用RIFE HDv2模型对包含建筑的视频进行插帧时发现建筑上的纹理插帧效果比较差，不知道你有没有什么建议可以缓解这一问题。我把测试用的视频放在下面的链接中供你测试。
![image](https://user-images.githubusercontent.com/16739780/117538678-e36b0c00-b039-11eb-9135-85c3b6ae736c.png)

https://drive.google.com/file/d/1t9BYJEFN-tRu9sex5FtOwDiZnvXeYBfu/view?usp=sharing

**Comment by hzwer** [comment]
目前我发现可以对光流的平滑性进行约束来缓解这一问题

**Comment by BoyuanJiang** [comment]
光流的平滑性约束是一种loss吗？有没有相关的论文或者实现可供参考呢

**Comment by hzwer** [comment]
https://github.com/lliuz/ARFlow/blob/master/losses/loss_blocks.py#L87 参考无监督光流的方法
