### ISSUE TITLE
Rapid Movement Artefacts

### ISSUE THREAD

**Issue by pepinu** [hzwer/arXiv2020-RIFE#155]
I've been testing rife on cartoon network's animation, to see how it handles rapid synthetic movement. I took a fragment of [this](https://www.youtube.com/watch?v=SRoA9ZSYV3o) scene, dropped frames to 1/4 of the original, and then used rife x4 model to get back the same result frame-wise. The result has shown artefacts I did not expect at all. The following are interim frames:

<img width="626" alt="Screenshot 2021-05-10 at 10 12 10" src="https://user-images.githubusercontent.com/7212724/117629063-11576a00-b17a-11eb-8028-05d6c7b514f8.png">

<img width="635" alt="Screenshot 2021-05-10 at 10 12 16" src="https://user-images.githubusercontent.com/7212724/117629052-0ef51000-b17a-11eb-9980-50b60cd316c4.png">

<img width="633" alt="Screenshot 2021-05-10 at 10 12 29" src="https://user-images.githubusercontent.com/7212724/117629044-0c92b600-b17a-11eb-8f80-36a27d0a87a7.png">

<img width="628" alt="Screenshot 2021-05-10 at 10 12 38" src="https://user-images.githubusercontent.com/7212724/117629027-0a305c00-b17a-11eb-8894-7083a86d2803.png">

<img width="628" alt="Screenshot 2021-05-10 at 10 12 43" src="https://user-images.githubusercontent.com/7212724/117629005-04d31180-b17a-11eb-86e7-b504d6ee75d3.png">

I suspect the problem lays with rife being dependent on the flow of the images, hence creating something shown above. I wonder though, are there any 'tricks' to solve this? Maybe a particular kind of training?

Best regards

**Comment by hzwer** [comment]
I'm waiting for a animation training dataset: https://github.com/lisiyao21/AnimeInterp/
Their work also proposes some interesting method.

**Comment by pepinu** [comment]
thanks, their work looks very promising!

However, I wonder how much of the result lays on the dataset vs the method itself.
