### ISSUE TITLE
球状物体插帧失败

### ISSUE THREAD

**Issue by dawei03896** [hzwer/arXiv2020-RIFE#156]
作者你好，我尝试使用RIFE HDv2模型对包含球类的视频进行插帧时发现插帧效果比较差，不知道你有没有什么建议可以缓解这一问题。我把测试用的图片放在下面。
![Beanbags](https://user-images.githubusercontent.com/84013536/117799814-19500080-b285-11eb-8083-e7c617fcae91.png)

**Comment by YiWeiHuang-stack** [comment]
scale调成0.25或者0.5试试

**Comment by hzwer** [comment]
v3.8 没有完美解决，感觉小物体得用前向流才能做好
![img0](https://user-images.githubusercontent.com/10103856/123043030-466a0400-d42a-11eb-8f4c-c3d3310dcaca.png)
![img1](https://user-images.githubusercontent.com/10103856/123043041-4a962180-d42a-11eb-82a5-72b5956bb892.png)
![img2](https://user-images.githubusercontent.com/10103856/123043044-4b2eb800-d42a-11eb-9c62-fea00da5e263.png)

**Comment by dawei03896** [comment]
比之前要好，看到rife3.x后期的工作，把ContextNet和FusionNet都拿掉了，想请教一下，这个是处于什么考虑？和之前相比，效果上有什么影响没？

**Comment by hzwer** [comment]
@dawei03896 因为从观感上看，去掉它们对视频的视觉效果影响较小，为了加速的考虑就去掉了

**Comment by dawei03896** [comment]
@hzwer 看rife3.8版本的训练代码，
1. 在update()函数中，对loss_smooth = self.sobel(flow[2], flow[2]*0).mean()的计算不太理解，能否大概讲讲？
2. 在loss计算部分感觉代码不是太完整，后续是否有完整的训练代码给出？
非常感谢！

**Comment by hzwer** [comment]
@dawei03896 有些代码只是实验性的；v3 以后的算法短期内无开源计划，原因是我们暂时没有专利也没有论文发表
