### ISSUE TITLE
question about figure 5 in your paper

### ISSUE THREAD

**Issue by btwbtm** [hzwer/arXiv2020-RIFE#157]
Hi, I am quite confused about figure 5. I can (if I am not wrong) understand the blurry motion boundaries in the middle images as F_t->0 and F_t->1 are reversed from F_0->t and F_1->t respectively and naturally there are some misalignment. But for IFNet, since you let F_t->1 = -(1-t)/t*F_t->0, when t=0.5, F_t->0 and F_t->1 are identical (with opposite sign). What do you want to show here? Or I misunderstand anything?

**Comment by hzwer** [comment]
"But for IFNet, since you let F_t->1 = -(1-t)/t*F_t->0, when t=0.5, F_t->0 and F_t->1 are identical (with opposite sign). What do you want to show here? Or I misunderstand anything?"
It seems the old version of our paper. I think you may refer to updated one https://arxiv.org/pdf/2011.06294.pdf

**Comment by btwbtm** [comment]
Thx for your prompt reply. It seems that figure 5 remains the same in the newest version. Can you briefly introduce how you make column 3 images?

**Comment by hzwer** [comment]
Combination: F_t->0 = (0.5 * F_0->1 + F_1->0 * (-0.5)) / 2, refer to SuperSlomo
F_0->1 and F_1->0 are estimated by LiteFlownet.
IFNet: F_t -> 0 directly estimated by IFNet
