### ISSUE TITLE
IFNet预测中间光流

### ISSUE THREAD

**Issue by dawei03896** [hzwer/arXiv2020-RIFE#159]
大佬你好，我用RIFE训练自己的数据，在训练IFNet时，需要用到光流数据作为监督，想问一下，这个4通道的光流的标签是不是将I0->I1的光流F0与I1->I0的光流F1，进行concat得到的？

**Comment by hzwer** [comment]
Each sample includes images (I0 I1 Imid : 9 x 256 x 448), and optical flow (flow_t0, flow_t1: 4, 256, 448).
是 mid->0 和 mid->1 的两个光流 concat

**Comment by dawei03896** [comment]
1. 感谢回复。所以，对于Vimeo90K就是算im2->im1和im2->im3的光流。
2. 你在ReadMe里提到 we use the optical flow labels generated on 2X size images using official released model，这是有什么特殊原因？还是pytorch-liteflownet网络要求的？

**Comment by hzwer** [comment]
1. 对的
2. 因为我发现在2倍分辨率的图上估计光流似乎看起来更准了，我后续做了一些实验感觉光流标签质量对最终结果影响并不是很大；只是因为我一开始这么做了所以就说明一下

**Comment by dawei03896** [comment]
好的，多谢大佬指教。
