### ISSUE TITLE
Problems in inference_img.py

### ISSUE THREAD

**Issue by kankj** [hzwer/arXiv2020-RIFE#16]
I use 

> $ python3 inference_img.py --img img0.png img1.png --times=4

, and I got this problem `interpolate() got an unexpected keyword argument 'recompute_scale_factor'` in **IFNet.py line 95**. Could you help me find out what happened, thanks

**Comment by hzwer** [comment]
I fix it. Sorry we did not consider the old version of pytorch.

**Comment by kankj** [comment]
It works fine, thank you
