### ISSUE TITLE
Don't mix audio back when input is GIF

### ISSUE THREAD

**Issue by Pythonic456** [hzwer/arXiv2020-RIFE#160]
I am trying to use RIFE to increase the FPS of a GIF.
However, when it attempts to mix the audio back in, it fails, as GIFS have no sound.
Is there a way to prevent it from attempting to mix back in the audio?

Thanks!

**Comment by hzwer** [comment]
Hello. Will this operation cause the result to fail? Can we ignore this error?

**Comment by Pythonic456** [comment]
Hi. Yes, this will result in no output file, and yes, we can ignore this error actually.
I found out that if you just specify the output fps (`--fps=60`) then it doesn't try adding the audio back.

Although it would be nice to have an option for disabling/removing sound.
