### ISSUE TITLE
Performance of v3 model

### ISSUE THREAD

**Issue by hzwer** [hzwer/arXiv2020-RIFE#161]
I'm not sure if v3 model can beat v2.4 model because the scale hypermeter is very sensitive after v3 model.
Anyone can help to test some hard cases?

**Comment by n00mkrad** [comment]
2D Animation, 1.8 vs 2.3 vs 2.4 vs 3.0

![koroVibeFrame23-Comp-1 8-2 3-2 4-3 0](https://user-images.githubusercontent.com/61149547/118358103-96c58a80-b57d-11eb-98d2-003fb26329bd.gif)

**Comment by n00mkrad** [comment]
Live-Action with movement, 2.3 vs 2.4 vs 3.0

![2 3-2 4-3 0](https://user-images.githubusercontent.com/61149547/118358113-a47b1000-b57d-11eb-8844-8d746c42798b.gif)

The scale does look a bit off here compared to the old models.

**Comment by YiWeiHuang-stack** [comment]
> 2D Animation, 1.8 vs 2.3 vs 2.4 vs 3.0
> 
> ![koroVibeFrame23-Comp-1 8-2 3-2 4-3 0](https://user-images.githubusercontent.com/61149547/118358103-96c58a80-b57d-11eb-98d2-003fb26329bd.gif)

Can you provide two frames before and after, thank you

**Comment by n00mkrad** [comment]
> Can you provide two frames before and after, thank you

Before
![00000021-rife30](https://user-images.githubusercontent.com/61149547/118360265-27ed2f00-b587-11eb-9552-02301074e5ee.png)

After
![00000027-rife30](https://user-images.githubusercontent.com/61149547/118360284-320f2d80-b587-11eb-937c-ebb1008f068f.png)
