### ISSUE TITLE
Question about visualization of flow generated by IFNet

### ISSUE THREAD

**Issue by Someone-LikeU** [hzwer/arXiv2020-RIFE#162]
Hi, I use your IFNet_HDv2 model to get flow of one pair of images from Viemo90K, they are:
![I0](https://user-images.githubusercontent.com/57308494/118361392-d9a75280-b5bd-11eb-8901-e65f080f2b40.png)I0.png
![I1](https://user-images.githubusercontent.com/57308494/118361407-eaf05f00-b5bd-11eb-9fa2-f107a4c00032.png)I1.png
then I use the visualization way from [this blog](https://blog.csdn.net/qq_34535410/article/details/89976801)  to get the visualization of the flow generated by IFNet, however, I get this result:
![his_F4_ft0](https://user-images.githubusercontent.com/57308494/118361611-c943a780-b5be-11eb-993f-17a67f55b38d.png)It looks so bad, but, when I use the same way to visualize the flow generated by the LiteFlowNet you mentioned in your README, it looks like this:
![ft0](https://user-images.githubusercontent.com/57308494/118361829-9cdc5b00-b5bf-11eb-98fc-bbc92dd970b4.png)
looks good. I wonder if my visualization method is wrong. Can you tell me how you visualize the flow generated by IFNet, like the Figure 5. you showed in your paper?

**Comment by hzwer** [comment]
![image](https://user-images.githubusercontent.com/10103856/118364651-e8950180-b5cb-11eb-8bdc-7f0e3927a115.png)

**Comment by Someone-LikeU** [comment]
Thanks a lot, I have tried the function flow2rgb, and the results looks good.
