### ISSUE TITLE
No output file

### ISSUE THREAD

**Issue by Pythonic456** [hzwer/arXiv2020-RIFE#165]
When running:
`python3 inference_video.py --ext=4 --video=video.mp4 --scale=1 --fps=240 `
It renders more frames, and does its thing.
But there is no output file, do you know how to fix this?
I am using `--fps=240` to not try to merge audio.

Thanks!

**Comment by hzwer** [comment]
It should not be --ext ...
--exp

**Comment by Pythonic456** [comment]
ah yes, thanks!
