### ISSUE TITLE
Question about SSIM

### ISSUE THREAD

**Issue by Someone-LikeU** [hzwer/arXiv2020-RIFE#166]
Hi, here i am again, in your train code, i only see the code for PSNR, but no SSIM part, could you please tell me where or how you compute it? Thanks a lot and thank you very much.

**Comment by hzwer** [comment]
Hello, SSIM calculation is time-consuming, so it is not implemented in train.py.
Please refer to https://github.com/hzwer/arXiv2020-RIFE/blob/9003b84c891bafd4f2f95f0483bd050b5466f83a/benchmark/Vimeo90K.py#L35

**Comment by Someone-LikeU** [comment]
Get it, thank you again.
