### ISSUE TITLE
可以和mpv player配合使用，实时插帧播放吗

### ISSUE THREAD

**Issue by b4imetu** [hzwer/arXiv2020-RIFE#169]
可以和[mpv player](https://mpv.io/installation/)配合使用，实时插帧播放吗

**Comment by hzwer** [comment]
目前模型太重了，因此这种应用的开发还不在考虑范围内
预计下半年会有支持 1080p 以上的实时插帧模型，届时有望将模型嵌入播放器或者硬件

**Comment by b4imetu** [comment]
了解，感谢
