### ISSUE TITLE
Non-Windows - Multiprocessing for ~2x processing speed

### ISSUE THREAD

**Issue by Eonzenex** [hzwer/arXiv2020-RIFE#17]
I profiled the code and you can expect roughly another 2x processing speed increase if you create a multiprocessing script and split the inferences apart from the image writing.

Unfortunately I just found out the hard way you cannot pipe CUDA tensors on Windows, but Linux systems should be able to do this.

**Comment by hzwer** [comment]
It may be possible to use pytorch's dataloader to complete this series of things, but it may require writing a lot of code.

**Comment by hzwer** [comment]
We should first process mp4 into pngs, then read pngs through dataloader multi-thread, and then write it out in multi-thread.

**Comment by hzwer** [comment]
I studied the performance bottleneck, and it seems that moving GPU data to the cpu is also a bottleneck. I don't know how to continue to optimize.

**Comment by Eonzenex** [comment]
Good job on the latest optimization, the README says you got roughly +30% but on my machine it was closer to +60%!

Yes that is where a lot of the sluggishness comes from unfortunately.
I wonder if there's a way of writing several images to a video file sequentially? Could be a way to speed that up.
It may also be faster to run several inferences in a row then move all of them to the CPU at once. Could send them to a new process to write then continue onto the next batch of inferences?

**Comment by hzwer** [comment]
I wrote a multithread script, get another 30% speedup!

**Comment by Eonzenex** [comment]
Nice job! That's awesome news!
