### ISSUE TITLE
cost compared to CDFI

### ISSUE THREAD

**Issue by ECEMACHINE** [hzwer/arXiv2020-RIFE#170]
Hello, thanks for your work! 
I found a very wired problem. When I interpolated the same video using CDFI and RIFE, I found that every inference time RIFE was much much faster than CDFI, which was about 0.01s and CDFI was 0.03s. This was totally using your code inference_video.py. I just replaced the model by CDFI.
However, when I used your code inference_img.py to infer the image not video and CDFI used their code inference_twoframe.py, I found that the for the same size images, RIFE was slower than CDFI, about RIFE 0.8 and CDFI 0.3.

The only difference except the model was that RIFE uses the torch.from_numpy but CDFI uses the torchvision.transform.ToTensor. I don't really know if this is the reason that influence the cost.

Thanks advance.

**Comment by hzwer** [comment]
Hi, the default setting of rife inference_img.py will interpolate 16x imgs. Did you notice that?

**Comment by ECEMACHINE** [comment]
> Hi, the default setting of rife inference_img.py will interpolate 16x imgs. You may ignore --exp=1? In my test, RIFE is about 2-3 times faster than CDFI.

Yes, I set the exp = 1 , I just test the inference function time. I found that just for the infer function, CDFI was a little faster than RIFE. But for RIFE I used the RIFE code, for CDFI I used the CDFI code. I mean maybe the data preprocess pipeline was the key?

**Comment by hzwer** [comment]
All programs are running on the GPU?

**Comment by ECEMACHINE** [comment]
> All programs are running on the GPU? Would you mind telling us about the resolution of your test image? Another possibility is that RIFE will write to the cache during the first inference.
Yes. On the same machine. And the resolution is 600x600. I just randomly find 2 images and resize it to 600x600. I just interpolate 1 frame between 2 images, and I just test the inference function not invloving any I/O options. I am very wired too since when infer video RIFE is so faster...

**Comment by ECEMACHINE** [comment]
> All programs are running on the GPU? Would you mind telling us about the resolution of your test image? Another possibility is that RIFE will write to the cache during the first inference.

Okay, maybe actually the pipeline influences. I use CDFI code to RIFE model, I found that RIFE is faster than CDFI. Maybe that torchvision ToTensor is faster than torch tensor?

**Comment by hzwer** [comment]
I test 600x600 on a 2080ti gpu and get 0.113s for RIFE. Do you use torch.cuda.synchronize() before time.time()?

**Comment by ECEMACHINE** [comment]
> I test 600x600 on a 2080ti gpu and get 0.113s for RIFE. Do you use torch.cuda.synchronize() before time.time()?

Okay, thanks so much! I got it！
