### ISSUE TITLE
关于hdv2和hdv3模型的复现

### ISSUE THREAD

**Issue by tqyunwuxin** [hzwer/arXiv2020-RIFE#172]
您好，
     我复现了hdv2和hdv3模型，但是和您提供的结果总有一些差距。
     配置超参数： weight_decay=1e-4, learing rate:3e-4 *mul ，vgg loss，还有 #146 中提到的数据增广方式，patch size 256，训练300epoch。
    我看您在hdv2和v3提供的版本中，模型结构都没有变化，它们都有什么区别呢？除了我上面的配置，想要达到您的效果还有哪些没有做到呢？

**Comment by hzwer** [comment]
你好，你说的差距能不能再详细说一下
我尝试了很多操作，有一些小结论：
a. 训练 1000 epoch 能改善很多 hard case
b. 增广 2x 4x 可以都加入
c. 加一些颜色空间增广感觉有用
d. 对光流加平滑 loss 能改善一些奇怪 pattern
e. vgg + l1 loss 会比单纯 vgg loss 少一些奇怪的 artifacts

**Comment by tqyunwuxin** [comment]
> 你好，你说的差距能不能再详细说一下
> 我尝试了很多操作，有一些小结论：
> a. 训练 1000 epoch 能改善很多 hard case
> b. 增广 2x 4x 可以都加入
> c. 加一些颜色空间增广感觉有用
> d. 对光流加平滑 loss 能改善一些奇怪 pattern
> e. vgg + l1 loss 会比单纯 vgg loss 少一些奇怪的 artifacts
> 主要问题是我还没有建立比较好的视觉效果评价指标，很多时候就是对着几张 hard case 调的

1、多谢回复，我看差距，主要是运动物体边缘会出现残缺，有时候还会一些格子出现。

**Comment by tqyunwuxin** [comment]
> 你好，你说的差距能不能再详细说一下
> 我尝试了很多操作，有一些小结论：
> a. 训练 1000 epoch 能改善很多 hard case
> b. 增广 2x 4x 可以都加入
> c. 加一些颜色空间增广感觉有用
> d. 对光流加平滑 loss 能改善一些奇怪 pattern
> e. vgg + l1 loss 会比单纯 vgg loss 少一些奇怪的 artifacts
> 主要问题是我还没有建立比较好的视觉效果评价指标，很多时候就是对着几张 hard case 调的

1、多谢回复，我看差距，主要是运动物体边缘会出现残缺，有时候还会一些格子出现。

**Comment by tqyunwuxin** [comment]
1、多谢回复，我看差距，主要是运动物体边缘会出现残缺，有时候还会一些格子出现。

**Comment by tqyunwuxin** [comment]
> 你好，你说的差距能不能再详细说一下
> 我尝试了很多操作，有一些小结论：
> a. 训练 1000 epoch 能改善很多 hard case
> b. 增广 2x 4x 可以都加入
> c. 加一些颜色空间增广感觉有用
> d. 对光流加平滑 loss 能改善一些奇怪 pattern
> e. vgg + l1 loss 会比单纯 vgg loss 少一些奇怪的 artifacts
> 主要问题是我还没有建立比较好的视觉效果评价指标，很多时候就是对着几张 hard case 调的


多谢回复 
1、我看差距，主要是运动物体边缘会出现残缺，有时候还会有一些格子状artifacts出现。
2、发现目前模型对于带字幕的插帧会出现字幕扭曲，对于带运动模糊（应该属于hardcase）的插帧，出现问题的几率比较大
3、您 说 的 d点 “平滑loss”是指 smooth L1 loss吗，我看代码目前是Charbonnier ，两个都用取平均 ，还是只用 smooth L1 loss？

**Comment by hzwer** [comment]
我说的平滑 loss 是指图像梯度 loss，类似 tv loss 这种，加在光流上会有用
可能字幕要加一个 mask 抠出来，但我还没有做

**Comment by KevenLee** [comment]
我看你提供的V3模型参数里面，有很多这样的权重，'block_tea.conv2.0.weight', 'block_tea.conv2.0.bias', 'block_tea.conv2.1.weight', 
但是，在推理的时候没有用到，是不是这些权重仅是训练的时候提供信息，推理的时候完全无视？
另外我看 v3 里面有
        # self.contextnet = Contextnet()
        # self.unet = Unet()
还有这样的注释代码，
        '''
        c0 = self.contextnet(img0, flow[:, :2])
        c1 = self.contextnet(img1, flow[:, 2:4])
        tmp = self.unet(img0, img1, warped_img0, warped_img1, mask, flow, c0, c1)
        res = tmp[:, 1:4] * 2 - 1
        '''
这些仅用于 v3 的训练？

**Comment by hzwer** [comment]
@KevenLee 是的，v3.5 后用了一种特别的模型蒸馏，还未整理开源

**Comment by KevenLee** [comment]
> @KevenLee 是的，v3.5 后用了一种特别的模型蒸馏，还未整理开源

后续有开源的计划么？

**Comment by KevenLee** [comment]
> @KevenLee 是的，v3.5 后用了一种特别的模型蒸馏，还未整理开源

蒸馏之后，性能相对蒸馏之前有大幅提升？

**Comment by hzwer** [comment]
@KevenLee 暂时没有计划 因为RIFE还没找到会议或期刊接受，原计划它们应该是RIFE的后续工作

**Comment by KevenLee** [comment]
RIFE 没中顶会？没天理啊

**Comment by hzwer** [comment]
@KevenLee 被拒了两回了而且分很低 说多都是泪。。。

**Comment by KevenLee** [comment]
> @KevenLee 被拒了两回了而且分很低 说多都是泪。。。

但，RIFE 会更加容易落地，相对那些笨重的模型，rife 在效果和性能上均衡上，是十分优秀的作品了，简直是工业实时应用的救星啊

**Comment by hzwer** [comment]
@KevenLee 感谢你的认可，希望能尽早发表吧 hhh
