### ISSUE TITLE
How to use the new v3.2 model

### ISSUE THREAD

**Issue by Tsubajashi** [hzwer/arXiv2020-RIFE#173]
Hey Hzwer, thanks for updating the models.
im having issues with using the new v3.2 model, it seems to stop working and just states this error:
`RuntimeError: Error(s) in loading state_dict for IFNet:
    Unexpected key(s) in state_dict: "contextnet.conv1.conv1.0.weight", "contextnet.conv1.conv1.0.bias", "contextnet.conv1.conv1.1.weight", "contextnet.conv1.conv2.0.weight", "contextnet.conv1.conv2.0.bias", "contextnet.conv1.conv2.1.weight", "contextnet.conv2.conv1.0.weight", "contextnet.conv2.conv1.0.bias", "contextnet.conv2.conv1.1.weight", "contextnet.conv2.conv2.0.weight", "contextnet.conv2.conv2.0.bias", "contextnet.conv2.conv2.1.weight", "contextnet.conv3.conv1.0.weight", "contextnet.conv3.conv1.0.bias", "contextnet.conv3.conv1.1.weight", "contextnet.conv3.conv2.0.weight", "contextnet.conv3.conv2.0.bias", "contextnet.conv3.conv2.1.weight", "contextnet.conv4.conv1.0.weight", "contextnet.conv4.conv1.0.bias", "contextnet.conv4.conv1.1.weight", "contextnet.conv4.conv2.0.weight", "contextnet.conv4.conv2.0.bias", "contextnet.conv4.conv2.1.weight", "unet.down0.conv1.0.weight", "unet.down0.conv1.0.bias", "unet.down0.conv1.1.weight", "unet.down0.conv2.0.weight", "unet.down0.conv2.0.bias", "unet.down0.conv2.1.weight", "unet.down1.conv1.0.weight", "unet.down1.conv1.0.bias", "unet.down1.conv1.1.weight", "unet.down1.conv2.0.weight", "unet.down1.conv2.0.bias", "unet.down1.conv2.1.weight", "unet.down2.conv1.0.weight", "unet.down2.conv1.0.bias", "unet.down2.conv1.1.weight", "unet.down2.conv2.0.weight", "unet.down2.conv2.0.bias", "unet.down2.conv2.1.weight", "unet.down3.conv1.0.weight", "unet.down3.conv1.0.bias", "unet.down3.conv1.1.weight", "unet.down3.conv2.0.weight", "unet.down3.conv2.0.bias", "unet.down3.conv2.1.weight", "unet.up0.0.weight", "unet.up0.0.bias", "unet.up0.1.weight", "unet.up1.0.weight", "unet.up1.0.bias", "unet.up1.1.weight", "unet.up2.0.weight", "unet.up2.0.bias", "unet.up2.1.weight", "unet.up3.0.weight", "unet.up3.0.bias", "unet.up3.1.weight", "unet.conv.weight", "unet.conv.bias".`
Not sure where that issue comes from, can you help there?

Feels like you missed to upload the other 2 pkls, contextnet and unet.

**Comment by BurguerJohn** [comment]
It seen there is two variables that was commented out on IfNet, you can add the vars again or load the dict using **strict=False**

**Comment by hzwer** [comment]
fixed at v3.3

**Comment by YiXinChenChen** [comment]
> fixed at v3.3

I use this model in you demo imgs, but I get the poor frame. 
Am I missing some parameter to tune?
![image](https://user-images.githubusercontent.com/19725109/121309578-ed33a800-c934-11eb-9a19-b633843d9810.png)

**Comment by hzwer** [comment]
Hi @YiXinChenChen, this model is optimized for high resolution scene. You may set scale_list = [1, 1, 1] or use models reported by our [paper](https://github.com/hzwer/arXiv2020-RIFE#evaluation).

**Comment by Tsubajashi** [comment]
interestingly, 3.3 works, but has lots of weird patterns on the interpolated images as if its not trained enough.
https://i.imgur.com/cpnY2TJ.png
the video file itself is 720p, so i think that should be enough, right?
