### ISSUE TITLE
光流的平滑性约束

### ISSUE THREAD

**Issue by dawei03896** [hzwer/arXiv2020-RIFE#175]
您好！
在“关于hdv2和hdv3模型的复现 #172”中您提到 对光流加平滑 loss，在https://github.com/lliuz/ARFlow/blob/master/losses/loss_blocks.py中需要传入光流和原始图像，想请教一下，原始图像用的是预测图像还是GT？

**Comment by hzwer** [comment]
理论上用的是 GT
但我试了一下直接将 gradient(flow) 加入 loss，效果比较好（仅限于视觉效果

**Comment by coolKeen** [comment]
> 理论上用的是 GT
> 但我试了一下直接将 gradient(flow) 加入 loss，效果比较好（仅限于视觉效果

您好，您的意思是dx, dy = gradient(flow); loss_flow = (dx.abs().mean() + dy.abs().mean())/2 吗

**Comment by hzwer** [comment]
@coolKeen 是的
