### ISSUE TITLE
Welcome to try v3.8 model

### ISSUE THREAD

**Issue by hzwer** [hzwer/arXiv2020-RIFE#176]
Based on the evaluation of dozens of videos, the v3.8 model has achieved an acceleration effect of more than 2X while surpassing the effect of the RIFEv2.4 model. And v3.8 can better handle 2d scenes.
At the same time, we welcome you to submit bad cases to help us in the future model improvement.

v3.8 model: https://github.com/hzwer/Practical-RIFE#model-list

**Comment by hzwer** [comment]
BTW, SVP project seems to be trying RIFE. https://www.svp-team.com/wiki/RIFE_AI_interpolation

**Comment by n00mkrad** [comment]
RIFE 3.6/3.7 don't seem to be faster than 3.1 for me.

3.1 gets me ~21 FPS, 3.6 and 3.7 get me ~14 FPS, both at the same resolution on my RTX 3070.

**Comment by hzwer** [comment]
I know. Because 3.1 version deleted a model branch, I think its effect is not very good. If you need faster speed, it is recommended to set scale=0.5.

**Comment by n00mkrad** [comment]
> Hi @n00mkrad. Because 3.1 version deleted a model branch, I think its effect is not good. If you need faster speed, it is recommended to set scale=0.5. Or I can provide a faster inference option in the next version.

Okay, I'll try changing the scale.

By the way, I heard that Pytorch 1.9 has an inference mode, could that be used to speed things up?

> Inference Mode API allows significant speed-up for inference workloads while remaining safe and ensuring no incorrect gradients can ever be computed. It offers the best possible performance when no autograd is required.

https://pytorch.org/blog/pytorch-1.9-released/

**Comment by HeylonNHP** [comment]
Models 3.1 to 3.5 work fine

Models 3.6 and 3.7 both crash with: `RuntimeError: CUDA error: an illegal memory access was encountered`

At Line 33 `self.flownet.to(device)` in `RIFE_HDv3.py`

**Comment by hzwer** [comment]
Would you mind changing IFNet_HDv3.py Line 90-91 to
flow = torch.zeros_like(x[:, :4]).to(device)
mask = torch.zeros_like(x[:, :1]).to(device)
I can't reproduce your problem, can you help me try this change please?
@HeylonNHP

**Comment by HeylonNHP** [comment]
It was the first thing I tried when I compared both versions. Sadly it makes no difference. I might need to play around with it more tomorrow.

**Comment by n00mkrad** [comment]
Alpha doesn't seem to work anymore in 3.6/3.7.

 I get this:

`RuntimeError: Given groups=1, weight of size [45, 11, 3, 3], expected input[1, 13, 36, 36] to have 11 channels, but got 13 channels instead`

**Comment by hzwer** [comment]
@n00mkrad @HeylonNHP I'm sorry that there may be some mistakes in v3.6-v3.7. I try my best to fix them in v3.8 model including alpha support and efficient inference.

**Comment by BurguerJohn** [comment]
3.8 is still looking a little more blurry than 3.1, it may perform better in other cases but still need to do more tests. It's already a lot better than 3.2

3.1
![0000000002 33](https://user-images.githubusercontent.com/32472975/122432816-07d8d300-cf6c-11eb-8fe4-3186859999a8.png)

3.8
![0000000002 33](https://user-images.githubusercontent.com/32472975/122432868-11623b00-cf6c-11eb-84e4-c991f235dc49.png)

**Comment by BurguerJohn** [comment]
It seen strange, but IFNet.block0 seen to be creating flows even for the same picture, generating a slight blur. Not sure if this is intentional.
```
flow = torch.zeros_like(x[:, :4]).to(device)
#Change warped_img1 to warped_img0
f0, m0 = block[0](torch.cat((warped_img0[:, :3], warped_img0[:, :3], mask), 1), flow, scale=ada_scale[i])
print(torch.min(flow), torch.max(flow))
print(torch.min(f0), torch.max(f0))
```
This generate some blur once warp is called, if the image is the same.

**Comment by HeylonNHP** [comment]
3.8 still crashes

**Comment by hzwer** [comment]
> 3.8 still crashes

I can not figure out why is it incompatible. I tested it on my mac, my linux and colab.

**Comment by HeylonNHP** [comment]
> 
> 
> > 3.8 still crashes
> 
> I can not figure out why is it incompatible. I tested it on my mac, my ubuntu worker and google colab.

I appreciate you trying to help. After digging through exceptions and stack traces for hours... I tried updating my pytorch from 1.8 to 1.9... and that alone fixed the issue 😂

**Comment by Narugakuruga** [comment]
3.8在很多方面都超过了2.4模型，特别是主观流畅度方面。
不过我还发现一些有瑕疵的场景，不知道是不是和低分辨率视频源有关。
![movie00_2X_60fps_Mux mp4_20210619_172216 088](https://user-images.githubusercontent.com/31060534/122637925-c9861400-d123-11eb-9c99-3d9e2839a97d.png)
RIFE 3.8
![movie00_W2xEX_VFI_mp4 mp4_20210619_172213 282](https://user-images.githubusercontent.com/31060534/122637943-d30f7c00-d123-11eb-8ab1-00314eb567db.png)
RIFE 2.4

前后两帧
![movie00 mp4_20210619_172248 414](https://user-images.githubusercontent.com/31060534/122637954-e02c6b00-d123-11eb-8b5f-b8e6c1caa2f2.png)
![movie00 mp4_20210619_172245 687](https://user-images.githubusercontent.com/31060534/122637956-e1f62e80-d123-11eb-9e26-8267aaf75a70.png)

**Comment by hzwer** [comment]
@Narugakuruga 非常感谢你的评测，可能有个原因是 v2.4 的训练时长长于 v3.7 10倍，同时计算量也是好几倍
我们目前已经搭建了一个大数据集 会持续继续优化

**Comment by YiXinChenChen** [comment]
There was a discussion about RGBA before, is this not supported now in V3.8？

**Comment by hzwer** [comment]
@YiXinChenChen It should be supported

**Comment by YiXinChenChen** [comment]
> @YiXinChenChen It should be supported
When I use two frames of RGBA img in inference_img.py, I get RGB imgs instead of the expected RGBA imgs. Am I doing something wrong?

**Comment by hzwer** [comment]
@YiXinChenChen 
<img width="627" alt="image" src="https://user-images.githubusercontent.com/10103856/123056891-f135ee80-d439-11eb-9a0b-06a72ad77191.png">

**Comment by Ibrohim112** [comment]
How to download rife v3.8 model on colab instead of 2x model, please send me a new codes, if possible.

**Comment by hzwer** [comment]
@lbrohim112 Please refer to https://github.com/hzwer/Practical-RIFE#model-list

**Comment by IbrohimBest** [comment]
> > > 3.8 still crashes
> > 
> > 
> > I can not figure out why is it incompatible. I tested it on my mac, my ubuntu worker and google colab.
> 
> I appreciate you trying to help. After digging through exceptions and stack traces for hours... I tried updating my pytorch from 1.8 to 1.9... and that alone fixed the issue 😂

How to update upto pytorch 1.9 on colab, it says you must update it for more good results, can you write code, cuz i want to fix things too, like you?
