### ISSUE TITLE
Static Frames

### ISSUE THREAD

**Issue by BASSG7** [hzwer/arXiv2020-RIFE#179]
Hi, I have the Static Frames warning message but my video is 30Fps and the output is very laggy and shorter than the input
I have 100 Static Frames, how can I resolve this

Thanks 🙏

**Comment by NotAndreh** [comment]
Once I also encountered this problem and I solved it by re-encoding the video

**Comment by BASSG7** [comment]
Hmmm okay I see, do you how can I re-encode my video please ?

**Comment by NotAndreh** [comment]
> Hmmm okay I see, do you how can I re-encode my video please ?
> 

I used [ffmpeg](https://www.ffmpeg.org/), you can try with this command 
`ffmpeg -i video.mp4 -c:v libx264 -pix_fmt yuv420p output.mp4`
This will re-encode the video using the h264 codec

**Comment by BASSG7** [comment]
> I used [ffmpeg](https://www.ffmpeg.org/), you can try with this command
> `ffmpeg -i video.mp4 -c:v libx264 -pix_fmt yuv420p output.mp4`
> This will re-encode the video using the h264 codec

Oh okay, but I’m using Google Colab, where do I place this line code ?

**Comment by NotAndreh** [comment]
> > I used [ffmpeg](https://www.ffmpeg.org/), you can try with this command
> > `ffmpeg -i video.mp4 -c:v libx264 -pix_fmt yuv420p output.mp4`
> > This will re-encode the video using the h264 codec
> 
> Oh okay, but I’m using Google Colab, where do I place this line code ?

You can install ffmpeg on Google Colab adding the code block and writing on it 
`!apt install ffmpeg`
Then you can execute the other command adding a `!` before it since it's a console command and not a python one

**Comment by hzwer** [comment]
This issue may be fixed, refer to #207.
