### ISSUE TITLE
Vimeo90K 样本问题

### ISSUE THREAD

**Issue by KevenLee** [hzwer/arXiv2020-RIFE#180]
Hi，你提供的 100 个 Vimeo90K 样本里面，img 的 gt 是不是弄反了啊？Vimeo90K 里面 im0, im1, im2是连贯的三帧，然后你提供的 i0 对应 im0， i1 对应 im1， gt 对应 im2, 这个是不是弄反了啊？我怎么感觉应该是 i0 对应 im0， i1 对应的应该是 im2, gt 对应的应该是 im1 才是啊。不知道理解对不对。

**Comment by hzwer** [comment]
Readme 里写的：
Each sample includes images (I0 I1 Imid : 9 x 256 x 448), and optical flow (flow_t0, flow_t1: 4, 256, 448).
确实跟官方不一致
