### ISSUE TITLE
关于非整数倍插帧

### ISSUE THREAD

**Issue by hahahaprince** [hzwer/arXiv2020-RIFE#181]
大佬你好，看到你文章里提到了做4x, 8x这种整数倍的插帧可以多次循环来做。那么对于24->60这种非整数倍呢，是否可以基于线性运动假设，通过$(t/0.5)*F_{t=0.5}$这样获得任意位置的光流呢，这样做会比其他的flow-based方法在效果有优势吗？不知道你有没有实验过，多谢～～

**Comment by hzwer** [comment]
可以的，好像 RIFE-App 开发者就是这么用的

**Comment by hahahaprince** [comment]
好的～

**Comment by ToBigboss** [comment]
> 可以的，好像 RIFE-App 开发者就是这么用的
这样做，效果比2的倍数插帧差不少，t=0.25  0.75两个时间点的图像跟t=0.5相差太小了，明显没有4x插值帧间变化明显

**Comment by hzwer** [comment]
@ToBigboss 这是去年中旬我们还没支持 RIFEm 的时候的解决方案
