### ISSUE TITLE
训练问题

### ISSUE THREAD

**Issue by KevenLee** [hzwer/arXiv2020-RIFE#182]
我在用你提供的 100sample 进行训练的时候，遇到下面的问题：
环境：
pytorch 版本 1.8.1
执行：  python3 -m torch.distributed.launch --nproc_per_node=4 train.py --world_size=4

(MEMC) xxxxxxxxx@bigo:/data3/xxxxxxxxx/work/demoRIFE/arXiv2020-RIFE$ python3 -m torch.distributed.launch --nproc_per_node=4 train.py --world_size=4
*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
*****************************************
/data3/xxxxxxxxx/anaconda3/envs/lib/python3.7/site-packages/torch/nn/functional.py:3503: UserWarning: The default behavior for interpolate/upsample with float scale_factor changed in 1.6.0 to align with other frameworks/libraries, and now uses scale_factor directly, instead of relying on the computed output size. If you wish to restore the old behavior, please set recompute_scale_factor=True. See the documentation of nn.Upsample for details.
  "The default behavior for interpolate/upsample with float scale_factor changed "
/data3/xxxxxxxxx/anaconda3/envs/lib/python3.7/site-packages/torch/nn/functional.py:3503: UserWarning: The default behavior for interpolate/upsample with float scale_factor changed in 1.6.0 to align with other frameworks/libraries, and now uses scale_factor directly, instead of relying on the computed output size. If you wish to restore the old behavior, please set recompute_scale_factor=True. See the documentation of nn.Upsample for details.
  "The default behavior for interpolate/upsample with float scale_factor changed "
/data3/xxxxxxxxx/anaconda3/envs/lib/python3.7/site-packages/torch/nn/functional.py:3503: UserWarning: The default behavior for interpolate/upsample with float scale_factor changed in 1.6.0 to align with other frameworks/libraries, and now uses scale_factor directly, instead of relying on the computed output size. If you wish to restore the old behavior, please set recompute_scale_factor=True. See the documentation of nn.Upsample for details.
  "The default behavior for interpolate/upsample with float scale_factor changed "
/data3/xxxxxxxxx/anaconda3/envs/lib/python3.7/site-packages/torch/nn/functional.py:3503: UserWarning: The default behavior for interpolate/upsample with float scale_factor changed in 1.6.0 to align with other frameworks/libraries, and now uses scale_factor directly, instead of relying on the computed output size. If you wish to restore the old behavior, please set recompute_scale_factor=True. See the documentation of nn.Upsample for details.
  "The default behavior for interpolate/upsample with float scale_factor changed "
training...
training...
training...
Killing subprocess 161896
Killing subprocess 161897
Killing subprocess 161898
Killing subprocess 161899
Traceback (most recent call last):
  File "/data3/xxxxxxxxx/anaconda3/envs/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/data3/xxxxxxxxx/anaconda3/envs/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/data3/xxxxxxxxx/anaconda3/envs/lib/python3.7/site-packages/torch/distributed/launch.py", line 340, in <module>
    main()
  File "/data3/xxxxxxxxx/anaconda3/envs/lib/python3.7/site-packages/torch/distributed/launch.py", line 326, in main
    sigkill_handler(signal.SIGTERM, None)  # not coming back
  File "/data3/xxxxxxxxx/anaconda3/envs/lib/python3.7/site-packages/torch/distributed/launch.py", line 301, in sigkill_handler
    raise subprocess.CalledProcessError(returncode=last_return_code, cmd=cmd)
subprocess.CalledProcessError: Command '['/data3/xxxxxxxxx/anaconda3/envs/bin/python3', '-u', 'train.py', '--local_rank=3', '--world_size=4']' died with <Signals.SIGSEGV: 11>.

**Comment by hzwer** [comment]
你好，这应该是说供数据的进程挂了
你先试试用单卡能不能训练，怀疑是 dataloader 初始化引起内存泄漏
