### ISSUE TITLE
frames interpolation not working sometimes

### ISSUE THREAD

**Issue by Tetsujinfr** [hzwer/arXiv2020-RIFE#185]
hi

I am testing/abusing this amazing repo slightly to do some image to image morphing.
That sometimes works quite well like in the gif example below.
![out](https://user-images.githubusercontent.com/29961693/126247059-8c06be2e-2734-4463-bb3d-e8f33e2db2cd.gif)

But sometimes, there there is just no interpolation happening, and for instance in 64X I get 63 frames identical to the input 0.png and 0000063.png is like the 1.png input. Example images not working here:

![0](https://user-images.githubusercontent.com/29961693/126247253-6a2be69c-3523-4140-b702-1650bf2089bb.png)
![1](https://user-images.githubusercontent.com/29961693/126247254-d67a6e27-ef65-4c27-99ea-1cc7c6b6d882.png)

Any idea why?
Is there some mechanism turning off interpolation if the frames are too dissimilar? (the working example above is from frames quite dissimilar I would think though)
thanks

**Comment by hzwer** [comment]
https://github.com/hzwer/arXiv2020-RIFE/blob/856d550d66e73c6f49ca59c249f3ddefd6cf7991/inference_video.py#L226
will skip interpolation if the frames are too dissimilar.

**Comment by Tetsujinfr** [comment]
Thanks a lot. That did the trick. Closing this thread.
