### ISSUE TITLE
about VGGPerceptualLoss

### ISSUE THREAD

**Issue by tqyunwuxin** [hzwer/arXiv2020-RIFE#186]
hi, The parameters are set as follows：
"indices = [2, 7, 12, 21, 30]
 weights = [1.0/2.6, 1.0/4.8, 1.0/3.7, 1.0/5.6, 10/1.5]"

What is your design based on? Have you ever tried to use only a single layer to calculate the loss?

**Comment by hzwer** [comment]
Hi, I copy this code from https://github.com/Vandermode/ERRNet/blob/master/models/losses.py
I also try directly optimizing lpips_vgg, and get similar affect.
I think use only a single layer may not be good.
