### ISSUE TITLE
Error with recompute_scale_factor=True 

### ISSUE THREAD

**Issue by EsteBran** [hzwer/arXiv2020-RIFE#19]
I've been trying to interpolate a 24fps mp4 video and this error gets thrown whenever I try to run either inference_video.py or inference_video_parallel.py. 

`C:\Python38\lib\site-packages\torch\nn\functional.py:3103: UserWarning: The default behavior for interpolate/upsample with float scale_factor changed in 1.6.0 to align with other frameworks/libraries, and now uses scale_factor directly, instead of relying on the computed output size. If you wish to restore the old behavior, please set recompute_scale_factor=True. See the documentation of nn.Upsample for details.
  warnings.warn("The default behavior for interpolate/upsample with float scale_factor changed "`

When running the parallel version, I also experience about a 20% decrease in speed of interpolation. On my 1070ti with latest drivers and cuda 11.0, a 1080p video has about 3.6 fps of interpolation. With the parallel script that speed reduces to around 2.9-3 fps.

**Comment by hzwer** [comment]
This warning will not affect the operation of the program, I will disable it. I will troubleshoot the problem that the parallel operation does not accelerate.

**Comment by hzwer** [comment]
I found out that this was due to a bottleneck in the data conversion from gpu to cpu, and I have now made some optimizations. Please help to test if it works.

**Comment by EsteBran** [comment]
![image](https://user-images.githubusercontent.com/32085355/99762229-07f01d80-2ac6-11eb-936d-e135f26fc414.png)



Ran the same 24fps ~9 second clip a few times using parallel and non parallel. Both show a bit of improvement in average speed. `inference_video.py` went from around 3.6it/s to 3.9it/s, and `inference_video_parallel` went from around 2.9 to 3.5-3.6it/s average. Don't know why parallel is slower, maybe it's because of the older architecture of 1000 series?

**Comment by hzwer** [comment]
I found a CPU data transmission bottleneck and made some optimizations, but it may require further experimentation.
It should have improved some speed now, try git pull and rerun the code.

**Comment by hzwer** [comment]
I should have solved this issue now!

**Comment by EsteBran** [comment]
Thanks for the quick fixes! 

The recompute error doesn't show anymore but the parallel script still isn't faster for my gpu over the normal `inference_video.py`. I'll try running it in linux later and see if that brings any improvements, since in another issue someone said windows can't pipe cuda tensors. I'll close this issue now.

**Comment by hzwer** [comment]
> Thanks for the quick fixes!
> 
> The recompute error doesn't show anymore but the parallel script still isn't faster for my gpu over the normal `inference_video.py`. I'll try running it in linux later and see if that brings any improvements, since in another issue someone said windows can't pipe cuda tensors. I'll close this issue now.

I need to study how to transfer data between cpu and gpu faster, which is the current bottleneck.

**Comment by hzwer** [comment]
On 720p video, I got 16 it/s when 2X interpolation. But 25 it/s if I drop the results without saving mp4.

**Comment by EsteBran** [comment]
I tried your newest commit, great job on the speedup! Now I'm getting around 6it/s on both parallel and normal scripts. Parallel script takes a bit longer to ramp up to full speed which loses a bit of time when interpolating short videos, but for longer ones (>1 minute) they take about the same time.
