### ISSUE TITLE
about the loss_G in v3.8 model

### ISSUE THREAD

**Issue by tqyunwuxin** [hzwer/arXiv2020-RIFE#190]
hello , in the file RIFE_HDv3.py, “loss_G = loss_cons + loss_smooth * 0.1”
do you only use these two loss for flowmap  to train the model， no loss_l1 or loss_vgg? and What is the weight between them？

**Comment by hzwer** [comment]
Hi, the code of RIFE_HDv3.py has not been verified, please use RIFE.py as a reference.
