### ISSUE TITLE
UnboundLocalError: local variable 'flow_gt' referenced before assignment

### ISSUE THREAD

**Issue by NEFUJoeyChen** [hzwer/arXiv2020-RIFE#195]
File "/data/home/chenjh/RIFE_NEW/train.py", line 84, in train
    flow_gt = flow_gt.permute(0, 2, 3, 1).detach().cpu().numpy()
大佬flow_gt参数未定义呀

**Comment by hzwer** [comment]
尝试修了一下，过两天我验证一下整个训练流程。
因为之前一直在改方法，没把代码都整理清楚。
