### ISSUE TITLE
24 to 60 fps?

### ISSUE THREAD

**Issue by spyro2000** [hzwer/arXiv2020-RIFE#196]
Hi there,

RIFE looks fantastic, but as fair as I know I only can enter integer numbers as scale factor, correct? So when I want to interpolate 24 fps to 60 (by far the most common case I suppose) I know no other way than interpolating to 120 (factor 5) and then drop any other frame to get 60. 

But even that doesn't seem to be possible as supported scale factors are only 2x, 4x, 8x (no 5x option).

So, is RIFE able to make 24 fps movie content run smooth on 60 Hz displays?

**Comment by hzwer** [comment]
So, is RIFE able to make 24 fps movie content run smooth on 60 Hz displays?
It has not been implemented at present. We can only approximate frame extraction after multiple interpolation of frames.

**Comment by vadash** [comment]
24 -> rife x2 -> 48 -> +4% speed up with mpv -> 50 fps  @ 50 hz display

Both my TV and monitors works fine with 50 hz but refuses to switch to 48 hz

**Comment by spyro2000** [comment]
There is simply not standard to display 48 fps on a display (only in Peter Jackson's head). That's why 60 fps for everything would be the best solution, but tell that to directors ;)

A speedup was common in past days to convert FILM content to PAL but that should be a thing of the past (you also have to speedup audio).

Guess we just have to wait until RIFE 2 to make this really useful. Looking forward! :)

**Comment by vadash** [comment]
+4% is nothing and dont affect user. Yep audio gets +4% too ofc

```
# "ReClock" replacement
video-sync=display-resample
video-sync-max-video-change=25
```

We are really close to realtime btw 
![image](https://user-images.githubusercontent.com/1397582/133657075-6231e7ab-5586-4955-9af5-132380651f7c.png)

its fp32 and fp16 models can get x2 boost

**Comment by Mr187k** [comment]
@vadash I'm running MadVR with Potplayer. Is there any way to make it play +4%? Running 48fps on 50Hz display has slight hiccups every second.
Btw with which GPU are you getting almost realtime performance?

**Comment by vadash** [comment]
> @vadash I'm running MadVR with Potplayer. Is there any way to make it play +4%? Running 48fps on 50Hz display has slight hiccups every second.
> Btw with which GPU are you getting almost realtime performance?

reclock for x86

**Comment by adahbingee** [comment]
This seems to be the training probem and model design for RIFE.
The simple 2x interpolate strategy makes it easy to find any video for training with dropping out every odd/even frames.
I'm also wondering what if RIFE can interpolate any phases in two frame not just phase 0.5.
If I do somthing time interpolate trick on flow output works?
@hzwer

**Comment by hzwer** [comment]
@adahbingee Unfortunately, we have not found a simple strategy to expand RIFE to such a scenario. DAIN, BMBC and EDSC are recommended.

**Comment by hzwer** [comment]
We support it in our new version paper, the model may be released within 1 month.

**Comment by spyro2000** [comment]
Wohooo, that came out of nowhere! Can't wait! :)))

**Comment by spyro2000** [comment]
Hi @hzwer, really looking forward, any news on this? :)

**Comment by vadash** [comment]
Is it worth it ? 
60hz: 12 original + 48 interpolated
50hz: 24 original + 24 interpolated

So 60 hz is twice as slow and have less OG frames. Just use 50 hz

**Comment by hzwer** [comment]
@spyro2000 Please check https://github.com/hzwer/Practical-RIFE/blob/6ae037d98b671f1221551e2bc819e8e2370f0aa2/inference_video.py#L174, we have already supported this feature.
I don't know if the downstream software is developed. As far as I know, SVFI based on RIFE already has this function.
@vadash Some display devices cannot directly support the 50hz format, maybe this is the important reason for this feature.

**Comment by spyro2000** [comment]
Pretty much any display runs on 60 Hz and even if it would support 50 Hz, browser, apps and videoplayer don't change the dispay's framerate.

**Comment by mirh** [comment]
> Pretty much any display runs on 60 Hz, especially PC, Notebooks and Smartphones by default.

Pretty much any display can be [forced](https://www.monitortests.com/forum/Thread-Custom-Resolution-Utility-CRU) to run at 50Hz then (droids may have been a bit [trickier](https://www.xda-developers.com/sony-xperia-xz-premium-hidden-120hz-screen-mode-razer-phone/) tbh, but today it's pretty [straightforward](https://android-developers.googleblog.com/2020/04/high-refresh-rate-rendering-on-android.html) too)

> And even if it would support 50 Hz, browser, apps and videoplayer don't change the dispay's framerate.

Apps and videoplayers totally can change the refresh rate. Of course they must be programmed to do so (like most games trivially are). 
Then browsers aren't ever going to support full mode changes for a number of reasons, but [soon enough](https://bugs.chromium.org/p/chromium/issues/detail?id=807406) you should be able to do everything with VRR (which can also be [hacked](https://forums.blurbusters.com/viewtopic.php?f=7&t=8889) into some older monitor btw). 

> So can RIFE now convert from 24 to 60 Hz in it's current version?

It is my understanding that the RIFEm model (that they added with their november paper) should support arbitrary interpolation factors. 
I'm unsure if they still nevertheless need to be integers, or 2.5 could be also possible.

**Comment by spyro2000** [comment]
>Pretty much any display can be [forced](https://www.monitortests.com/forum/Thread-Custom-Resolution-Utility-CRU) to run at 50Hz 

Yeah, good luck doing that from within a browser. ;)

>Apps and videoplayers totally can change the refresh rate. Of course they must be programmed to do so (like most games trivially are).

But they don't. And even if they are, they are not configured like that.

>It is my understanding that the RIFEm model (that they added with their november paper) should support arbitrary interpolation factors.

Highly appreciated :)

**Comment by mirh** [comment]
> But they don't.

They do, and people already told you about reclock here. 
MadVR and mpv are far better and more modern examples. 

> Yeah, good luck doing that from within a browser. ;)

https://github.com/w3c/html/issues/375#issuecomment-480620816
Even though (after checking more thoroughly) I'll grant to you that the ways of improving the standards of the web are immensely long and wide.

**Comment by spyro2000** [comment]
Seriously, I do not want to speedup a movie by 4% and then use Reclock or a VRR-Mode for browser or something just to view a movie without stutter. I did that 15 years ago and it did not work out at the long run, believe me. ;)

Instead, thats an excellent use case for frame interpolation. I just could convert a 24 fps source before uploading it to YouTube or sharing it otherwise. Everyone gets fluid motion on their display with default settings. So I highly appreciate it, that RIFE will be able to convert 24 fps to 60 fps in the future, looking forward. ;)

**Comment by vadash** [comment]
> RIFE will be able to convert 24 fps to 60 fps

A lot of tools already can do that 
![image](https://user-images.githubusercontent.com/1397582/198084303-b682c8c8-ef77-4276-8db8-0b3a7d47c71e.png)

Flowframes too
