### ISSUE TITLE
Google Colab

### ISSUE THREAD

**Issue by mjc619** [hzwer/arXiv2020-RIFE#2]
Willing to set up a Google Colab notebook or a Docker setup?
interested in seeing results for 3DCG interpolation

**Comment by hzwer** [comment]
Colab will be released today.

**Comment by hzwer** [comment]
Done.

**Comment by ak9250** [comment]
@hzwer similar to the dain video could you please combine the before and after videos into one video in the colab, I used ffmpeg to do that but since they will be out of sync maybe you are familiar with a better way to do it

**Comment by hzwer** [comment]
> @hzwer similar to the dain video could you please combine the before and after videos into one video in the colab, I used ffmpeg to do that but since they will be out of sync maybe you are familiar with a better way to do it
> ffmpeg 
> -i input1.mp4 
> -i input2.mp4 
> -filter_complex '[0:v]pad=iw*2:ih[int];[int][1:v]overlay=W/2:0[vid]' 
> -map [vid] 
> -c:v libx264 
> -crf 23 
> -preset veryfast 
> output.mp4

OK. I will provide a code for you soon.
