### ISSUE TITLE
TypeError when trying to output PNG frames

### ISSUE THREAD

**Issue by n00mkrad** [hzwer/arXiv2020-RIFE#20]
I'm getting this error if I add the --png argument:

`xception ignored in thread started by: <function clear_buffer at 0x00000158A426F310>
Traceback (most recent call last):
  File "inference_video_parallel.py", line 83, in clear_buffer
    cv2.imwrite('output/{:0>7d}.png'.format(cnt), i)
TypeError: unsupported format string passed to numpy.ndarray.__format__`

**Comment by hzwer** [comment]
Fixed.

**Comment by n00mkrad** [comment]
Thanks a lot!

I now get this:

`Traceback (most recent call last):
  File "inference_video_parallel.py", line 130, in <module>
    vid_out.release()
AttributeError: 'NoneType' object has no attribute 'release'`

However, this only seems to happen because the code path shouldn't run when --png is used.
