### ISSUE TITLE
Trying to inference video produce a runtime error

### ISSUE THREAD

**Issue by bfrancis98** [hzwer/arXiv2020-RIFE#201]
I put `demo.mp4` in the `arXiv2020-RIFE` folder. From the console, I ran `inference_video.py --exp=2 --video=demo.mp4`. The error in the txt is what I get. Not sure how to resolve this issue.
[arxiv2020-rife error.txt](https://github.com/hzwer/arXiv2020-RIFE/files/7243516/arxiv2020-rife.error.txt)

**Comment by hzwer** [comment]
It may be caused by mismatched code and model, you may begin with our colab demo. 
https://github.com/hzwer/arXiv2020-RIFE#arxiv--youtube--colab--tutorial--demo
