### ISSUE TITLE
can't train

### ISSUE THREAD

**Issue by debian-user-france1** [hzwer/arXiv2020-RIFE#202]
```    ~/arXiv2020-RIFE    main  python3 -m torch.distributed.launch --nproc_per_node=4 train.py --world_size=4
/home/france1/.local/lib/python3.9/site-packages/torch/distributed/launch.py:178: FutureWarning: The module torch.distributed.launch is deprecated
and will be removed in future. Use torch.distributed.run.
Note that --use_env is set by default in torch.distributed.run.
If your script expects `--local_rank` argument to be set, please
change it to read from `os.environ['LOCAL_RANK']` instead. See 
https://pytorch.org/docs/stable/distributed.html#launch-utility for 
further instructions

  warnings.warn(
WARNING:torch.distributed.run:*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed. 
*****************************************
Traceback (most recent call last):
Traceback (most recent call last):
  File "/home/france1/arXiv2020-RIFE/train.py", line 140, in <module>
Traceback (most recent call last):
  File "/home/france1/arXiv2020-RIFE/train.py", line 140, in <module>
  File "/home/france1/arXiv2020-RIFE/train.py", line 140, in <module>
    torch.cuda.set_device(args.local_rank)
  File "/home/france1/.local/lib/python3.9/site-packages/torch/cuda/__init__.py", line 264, in set_device
    torch.cuda.set_device(args.local_rank)
  File "/home/france1/.local/lib/python3.9/site-packages/torch/cuda/__init__.py", line 264, in set_device
    torch.cuda.set_device(args.local_rank)
  File "/home/france1/.local/lib/python3.9/site-packages/torch/cuda/__init__.py", line 264, in set_device
    torch._C._cuda_setDevice(device)
    RuntimeErrortorch._C._cuda_setDevice(device): 
CUDA error: invalid device ordinal
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
RuntimeError: CUDA error: invalid device ordinal
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
    torch._C._cuda_setDevice(device)
RuntimeError: CUDA error: invalid device ordinal
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 1 (pid: 651166) of binary: /usr/bin/python3
Traceback (most recent call last):
  File "/usr/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/france1/.local/lib/python3.9/site-packages/torch/distributed/launch.py", line 193, in <module>
    main()
  File "/home/france1/.local/lib/python3.9/site-packages/torch/distributed/launch.py", line 189, in main
    launch(args)
  File "/home/france1/.local/lib/python3.9/site-packages/torch/distributed/launch.py", line 174, in launch
    run(args)
  File "/home/france1/.local/lib/python3.9/site-packages/torch/distributed/run.py", line 689, in run
    elastic_launch(
  File "/home/france1/.local/lib/python3.9/site-packages/torch/distributed/launcher/api.py", line 116, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/france1/.local/lib/python3.9/site-packages/torch/distributed/launcher/api.py", line 244, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
***************************************
            train.py FAILED            
=======================================
Root Cause:
[0]:
  time: 2021-09-30_17:35:27
  rank: 1 (local_rank: 1)
  exitcode: 1 (pid: 651166)
  error_file: <N/A>
  msg: "Process failed with exitcode 1"
=======================================
Other Failures:
[1]:
  time: 2021-09-30_17:35:27
  rank: 2 (local_rank: 2)
  exitcode: 1 (pid: 651167)
  error_file: <N/A>
  msg: "Process failed with exitcode 1"
[2]:
  time: 2021-09-30_17:35:27
  rank: 3 (local_rank: 3)
  exitcode: 1 (pid: 651168)
  error_file: <N/A>
  msg: "Process failed with exitcode 1"
***************************************

```

**Comment by debian-user-france1** [comment]
   ~  python -m torch.device("cuda")                                                                                                                                                                                             1 ✘ 
zsh: number expected
    ~ 

**Comment by hzwer** [comment]
It seems that the latest version of torch is not compatible with the old version of the launcher. Would you mind using torch between 1.3 and 1.8 to try again?

**Comment by debian-user-france1** [comment]
Well, wich version do i have?

If you could explain how I can install it, yes

A problem is that the modules aren't in the requirements... Could you add them to the list or... whatever

**Comment by hzwer** [comment]
@debian-user-france1 
I modified requirement.txt, please see https://github.com/hzwer/arXiv2020-RIFE/blob/main/requirements.txt
You can use this command:
pip3 install torch==1.6.0 torchvision==0.7.0

**Comment by hzwer** [comment]
@debian-user-france1 You may use pip with too old version. Please try:
python3 -m pip install --upgrade pip

**Comment by debian-user-france1** [comment]
There was no message that pip is outdated

**Comment by debian-user-france1** [comment]
I tried to upgrade pip but it was already the newest version...

If we look at that:
`ERROR: Could not find a version that satisfies the requirement torch==1.6.0 (**from versions: 0.1.2, 0.1.2.post1, 0.1.2.post2, 1.7.1, 1.8.0, 1.8.1, 1.9.0, 1.9.1**)` 
We see wich versions are compatible with Python 3.9.7

**Comment by hzwer** [comment]
@debian-user-france1 You may try 1.7.1. I hope it will work.
pip3 install torch==1.7.1

**Comment by sabhiram6** [comment]
did u find solution for this issue ? FutureWarning: The module torch.distributed.launch is deprecated
and will be removed in future. Use torchrun.
Note that --use-env is set by default in torchrun.
If your script expects `--local-rank` argument to be set, please
change it to read from `os.environ['LOCAL_RANK']` instead. See 
https://pytorch.org/docs/stable/distributed.html#launch-utility for 
further instructions

  warnings.warn(
usage: train.py [-h] [--cfg CFG_FILE] [--num_workers NUM_WORKERS] [--stamp STAMP] [--imsize IMSIZE] [--batch_size BATCH_SIZE]
                [--train TRAIN] [--resume_epoch RESUME_EPOCH] [--resume_model_path RESUME_MODEL_PATH]
                [--multi_gpus MULTI_GPUS] [--gpu_id GPU_ID] [--random_sample]
train.py: error: unrecognized arguments: --local-rank=0
[2023-11-03 12:23:37,197] torch.distributed.elastic.multiprocessing.api: [ERROR] failed (exitcode: 2) local_rank: 0 (pid: 1206070) of binary:
in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
src/train.py FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2023-11-03_12:23:37
  host      : jupitor
  rank      : 0 (local_rank: 0)
  exitcode  : 2 (pid: 1206070)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
