### ISSUE TITLE
问题: Dataset有multiframes的时候，该如何prepare

### ISSUE THREAD

**Issue by chenyuZha** [hzwer/arXiv2020-RIFE#204]
你好，首先非常感谢在github上共享这个repo!

在用您release的model运行inference之后，我想尝试用customer dataset来训练。

我的dataset每一个video里面有24个frames,  所以目标就是生成中间的22个frames.

我参考了 一下在`dataset.py` 中的 `VimeoDataset` class, 发现在prepare的data的时候， 因为这个dataset每个video只有3个frames，所以return的都是 第一个和最后一个frame，要求interpolate的是中间的frame.

- 想请问一下如果我想interpolate多个frames，是有可能实现的吗? 

目前我已经开始训练了，我大概做了一个稍微的调整，就是input是第一个和最后一个frame， 要求predict中间的那个frame (第十二个frame)，然后Model的选择，我选的是 `RIFE.py`  和 `IFNet.py`，对应的生成Model应该是最robust的(**42.9MB**).
因为我的数据集比较单一，为了防止overfitting，我先预先load了你们release的Model, 然后继续训练。

- 但是我发现loss在几十个epoch之后，出现了井喷的状态，最后生成的Model在做inference的时候，完全生成不了中间的22个frames(全部都是黑图), 跟我一开始用您release的Model运行的结果相差甚远...

后来我尝试用另一个Model训练(`RIFE_HDV3.py`  和 `IFNet_HDV3.py`)(生成Model是12.2MB), 但是pytorch一直报错。

-` RuntimeError: Expected to have finished reduction in the prior iteration before starting a new one. This error indicates that your module has parameters that were not used in producing loss. You can enable unused parameter detection by (1) passing the keyword argument `find_unused_parameters=True` to `torch.nn.parallel.DistributedDataParallel`; (2) making sure all `forward` function outputs participate in calculating loss. If you already have done the above two steps, then the distributed data parallel module wasn't able to locate the output tensors in the return value of your module's `forward` function. Please include the loss function and the structure of the return value of `forward` of your module when reporting this issue (e.g. list, dict, iterable).
`
错误源头是在`RIFE_HDV3.py`中的 `update()`里的 `flow, mask, merged = self.flownet(imgs, scale=[4,2,1])`
我查了一下，出现这个错误原因是因为在 `forward()`的output里有些variables没有用来calculate loss. 我又去仔仔细细的查看了一下`IFNet_HDV3`下的`forward()` , 还是无果..

如果您有好的建议的话，不甚感谢!

**Comment by hzwer** [comment]
其实最近我也在研究 interpolate 多个 frames 的做法，我发现在这种场景下，用类似 softsplat 的方案是比较科学的
遇到 loss 爆炸的情况，建议调小学习率或调大 weight decay
这个报错我大概知道怎么解决，一是在 DDP 调用的时候写上 find_unused_parameters=True
二是把所有算出来的 loss 都加到总 loss 里，不想要的 loss 就写上 * 0

**Comment by hzwer** [comment]
@chenyuZha loss_G = loss_smooth * 0 + loss_l1 这样
感谢反馈，确实加数据量是很本质的做法

**Comment by NEFUJoeyChen** [comment]
我训练时也出现了梯度爆炸的情况，和你一样出现黑图，我加入了batch norm后重新训练则没有再出现过loss崩了的情况。

**Comment by chenyuZha** [comment]
你好，前段时间我做了一些不同的训练， 最近在分析每个model测试的结果。 在查看inference结果的时候，我注意到如果我的训练集中间的frame与我前后两个frames '离的比较远'的时候(运动幅度比较大), 在生成的frame里，图片偏远处的物体会比较模糊。

- 针对这一情况，我目前是增加了我的训练集，并且我是从另一个model fine-tuning。
想请教一下这个模糊的原因是因为

- 训练集的原因(中间frame 的 ground truth 有时候会有一些'抖动'的感觉)
- 还是model本身其实对于运动幅度较大的frame会有一些limitation?

谢谢你的回答!

**Comment by hzwer** [comment]
@chenyuZha 对，我觉得纯卷积对于捕捉大幅度的运动是有一些问题的

**Comment by chenyuZha** [comment]
谢谢您的回复! 
我最近在探索能否freeze**用小运动幅度的训练集训练的model**的一些layers, 然后fine-tuning一个大运动幅度的dataset。我查看了一下IFnet的arch，正如你所说是FCN。 这种情况下你比较建议我freeze哪些layers呢?

**Comment by hzwer** [comment]
@chenyuZha 我不确定，如果你只看效果的话，建议把 refinenet 扔了，把 IFBlock 加多一个 scale=8
