### ISSUE TITLE
Inference Stops at Specific Frame

### ISSUE THREAD

**Issue by therealkingoftheuniverse** [hzwer/arXiv2020-RIFE#210]
Inference Stop at a specific frame near the end of video (about 99% of the way through, just a few frames from the end) multiple times. 
The video is 1080p and 4X interpolation is applied to it.
What happens is the the once it reached this point, the process freezes forever and the gpu usage drops to 0.
No error message is visible. It looks perfectly normal expect the bar stops moving.
The output mp4 file from the already processed frames is also not able to be read.
This does not seem to happen on short videos.

What is causing this and how to fix this?
Also I know I am providing little information, I don't know what I information should provide, please tell me what additional stuff I need to provide.
Thanks in advance.

Also I am using torch 1.10.0+cu113 which is not allowed according to the requirement but I can't find the a way to install torch 1.6. Is this the problem?
Can be replicated on windows and ubuntu.

**Comment by hzwer** [comment]
Sorry, I wrote a bug yesterday. Please git pull the newest code and this issue should be fixed.

**Comment by therealkingoftheuniverse** [comment]
Thanks, it is fixed in the latest version.
