### ISSUE TITLE
请问为啥训练要用testlist.txt中的做validate？

### ISSUE THREAD

**Issue by DachunKai** [hzwer/arXiv2020-RIFE#211]
就我理解，不应该是train-val-test的模式吗？既然实验里在vimeo里面做test，在训练的时候testlist.txt里的不应该是不可见的吗？

**Comment by hzwer** [comment]
你说的没错，这只是为了画出最后的性能变化曲线
理论上不应该在测试集上调参
BTW，按我的经验，low-level 相关任务中还没看到过拟合的风险
