### ISSUE TITLE
Brightness of the original video is not preserved.

### ISSUE THREAD

**Issue by Snamdeo111** [hzwer/arXiv2020-RIFE#212]
The brightness level in the original video is not preserved.

Platform : Windows 10 & Google Colab
Train Log Source : RIFE_trained_model_HDv2.zip (present in the colab https://drive.google.com/uc?id=1wsQIhHZ3Eg4_AfCXItFKqqyDMB4NS0Yd)

The output video is brighter in comparison to the original video. i have tried both rife and practical rife. 

original video : https://ufile.io/8ojbk8oe

output video : https://ufile.io/vgk4vcy2

**Comment by hzwer** [comment]
This type of problem is caused by the codec and has nothing to do with the algorithm; the solution is to first convert the video to png losslessly, and then convert it back after interpolate the frame. 
You may refer to https://github.com/hzwer/arXiv2020-RIFE#software to find a suitable software.
