### ISSUE TITLE
About data augmentation in dataset.py

### ISSUE THREAD

**Issue by chenyuZha** [hzwer/arXiv2020-RIFE#214]
你好， 想请教一下data augmentation 中的 resize dimension是否会在一定程度上影响生成的frame质量。
          `  img0, gt, img1 = self.aug(img0, gt, img1, 224, 224)`

因为当我用`224 x 224`进行训练的时候，由于我的frame前中后运动幅度会比较大，所以生成的frame会有一定程度上的blurry。
后来我选择 `384 x 384`重新训练，blurry的程度得到了非常明显的改善，但是在30 epochs以后图像上生成 artefacts.

我的图片size是1280x720, 所以我认为一个更大一点的size会帮助model在训练中更好的学习。但是对于大的size，生成artefacts的原因可能是出自于reconstruction时候? 需要增加`kernel size` 吗?
谢谢您的解答!

**Comment by hzwer** [comment]
你好，可以在训练和测试的时候使用不对称的 scale；比如训练的时候 scale 改成 8, 4, 2

**Comment by chenyuZha** [comment]
我在训练的时候scale根据您之前的建议改成了 [8, 4, 2, 1]并且加了一个IFBlock。
所以在测试的384 x 384模型的时候，把scale改成[4, 2, 1]是吗?

**Comment by hzwer** [comment]
我觉得要看你的使用场景来决定，而且也不一定大分辨率就要大 size，有可能小分辨率但是时间间隔大也需要大 kernel size；这些可能需要做实验尝试

**Comment by chenyuZha** [comment]
谢谢您的解答!
