### ISSUE TITLE
New interpolation factors have "bouncy" motion in generated frames

### ISSUE THREAD

**Issue by tellovishous** [hzwer/arXiv2020-RIFE#219]
Hi there, wanted to report an issue I noticed with RIFE. n00mkrad from the Flowframes program directed me here.

I had heard that the RIFE model now supports multiple interpolation factors outside of x2,x4,x8,etc, and the Flowframes program was recently updated to support this. However, after some recent experiments it seems that there's something wrong with the interpolated motion in these new factors. The new frames generated from RIFE seem to have a "bouncy" motion between true frames and it's not smooth like it should be.

Here's a quick, crude example I made, a small gif going at 1 fps:
![MotionTest2](https://user-images.githubusercontent.com/17260813/144763325-5704a765-649c-491a-aeeb-5374906d8155.gif)
And here's the gif interpolated at x5 for 5 fps. Notice that it has uneven and pulsed motion:
![MotionTest-5x-RIFE-RIFE2 3-5fps2](https://user-images.githubusercontent.com/17260813/144763392-b8f11334-8ad3-4195-85fb-e72b3ddf4fba.gif)
For comparison, I tried using a different AI model (XFVI) that already works with multiple factors, and despite the distortion you should see that the motion is much smoother at the same x5 factor:
![MotionTest-5x-XVFI-X4K1000FPS-5fps2](https://user-images.githubusercontent.com/17260813/144763483-ce71871c-bb06-48c8-b8e0-f340d3bb38af.gif)
Lastly, I did this one more time with a normal x4 factor and it doesn't have the issue:
![MotionTest2-4x-RIFE-RIFE2 3-4fps](https://user-images.githubusercontent.com/17260813/144763809-af43cd67-f614-4835-a3e5-3022432e7b2b.gif)

I've tried using different versions of RIFE and they all seem to exhibit the same motion issue at non-standard factors. Not sure what the problem could be, but I'd like to have this problem fixed so that the new factors work properly.

Update: I did some more testing and it seems this is something that mostly happens using model versions prior to 3.9. 3.9 doesn't always have the bouncing problem with the new interpolation factors, but it can still happen with certain content in certain situations. I still think this is worth looking into.

**Comment by AIVFI** [comment]
I am curious if the same problem occurs with x5 interpolation for the RIFE_m model?

Which model gives better quality for typical x2 and x4 interpolation: RIFE v3.9 or RIFE_m?

**Comment by hzwer** [comment]
I found a bug on v3.9b model. It will be updated soon.
