### ISSUE TITLE
Need proper sync for buffer

### ISSUE THREAD

**Issue by VvvvvGH** [hzwer/arXiv2020-RIFE#22]
The buffer is not thread safe. It might result in generating broken frame. Better use queue for buffer.

https://github.com/hzwer/arXiv2020-RIFE/blob/da21de1c813ab1c91de091026706429f3cd89424/inference_video_parallel.py#L53
https://github.com/hzwer/arXiv2020-RIFE/blob/da21de1c813ab1c91de091026706429f3cd89424/inference_video_parallel.py#L125-L128

**Comment by n00mkrad** [comment]
+1

I keep getting glitched frames because the buffer is not in sync.

**Comment by hzwer** [comment]
Done.
