### ISSUE TITLE
Can you release the training log on vimeo90k?

### ISSUE THREAD

**Issue by askerlee** [hzwer/arXiv2020-RIFE#228]
I've made some changes to RIFE, but not sure whether it helps or worsens. Could you kindly release the error log? It would serve as a reference before the training has finished. Thank you very much.

**Comment by hzwer** [comment]
<img width="305" alt="image" src="https://user-images.githubusercontent.com/10103856/148682778-0f0d00f9-c445-4a05-ac69-342866df465e.png"><img width="313" alt="image" src="https://user-images.githubusercontent.com/10103856/148682791-80902d89-76a1-4daa-afd6-adab54f10c4c.png"> 
<img width="289" alt="image" src="https://user-images.githubusercontent.com/10103856/148682812-dc2640fc-6d5c-4aef-8ad6-8cd6013696e4.png">

**Comment by askerlee** [comment]
Thank you! This is helpful. One more thing, could you please help me verify that the psnr I got in the first three evaluations are close to yours: 34.16, 34.67, 34.92? Just want to make sure that I've set up everything correctly.

**Comment by hzwer** [comment]
Yours are slightly higher, I think it's ok.

**Comment by askerlee** [comment]
Thank you so much @hzwer 😃

**Comment by askerlee** [comment]
BTW I got 36.04 psnr using your code (under default setting). I guess it corresponds to RIFE in table 2 of the paper? But it's much higher than the results you reported 😃

**Comment by hzwer** [comment]
@askerlee I report the results of Vimeo90K testing set. You may follow https://github.com/hzwer/arXiv2020-RIFE/blob/main/benchmark/Vimeo90K.py to test your trained model.

**Comment by askerlee** [comment]
I see I see. Sorry for the confusion.
