### ISSUE TITLE
Output videos are shorter than input videos

### ISSUE THREAD

**Issue by SleepingFox88** [hzwer/arXiv2020-RIFE#23]
Videos created with commands such as ``python3 inference_video.py --exp=1 --video=video.mp4`` are shorter than their source videos. How much shorter seems to vary significantly depending on the source video. I believe this to be due to dropped frames even though the ``--skip`` flag is not being used. ~~There is also the possibility of output video frames being out of order which may also affect timing~~ (my mistake that was part of the source video I used). I am working on providing examples for this.

This issue will cause desync between video and sound if it's added, as requested in #12

**Comment by hzwer** [comment]
I modified the thread synchronization code a few minutes ago, please help test it.

**Comment by SleepingFox88** [comment]
@hzwer I'm still having the same issue. With one of my files I am also getting ``Segmentation fault (core dumped)`` every attempted run at frame ``5137/5545.0``. or 93% progress. This could be related, though I am not sure that I get a segFault every time I get a shorter video. Interestingly the outputted video does not appear to be missing the last 7% of the video. The video is just played faster than it should be.

My input file has ``5544`` frames. doubling that, I'd expect an output file with around ``11088`` frames. However my output file (created after the segfault) has ``10272`` or 0.926% the expected number of frames.

**Comment by hzwer** [comment]
OK, I'll find a way to reproduce this issue.

**Comment by hzwer** [comment]
Fixed by using sk-video.

**Comment by SleepingFox88** [comment]
I'll try the update out.

Take note:

Of the 5 videos I just tested with. All of them ended in a segFault. 3/5 had the segFault on the last frame of the video (minor issue) 2/5 (the 4k videos) both segFaulted at 93%, resulting in a significant video speed increase.

![](https://i.imgur.com/qmZQlBq.png)

**Comment by SleepingFox88** [comment]
I am currently having difficulty getting ``pip install skvideo`` to work. 

I am getting ``ERROR: Failed building wheel for skvideo`` even though I believe I have wheel correctly installed. I will test more for this issue once I figure this out.

**Comment by hzwer** [comment]
You should use "pip install sk-video" to install it. It's weird though.

**Comment by SleepingFox88** [comment]
``sudo pip install scikit-video`` seemed to be an acceptable alternative. I found it from here https://github.com/scikit-video/scikit-video

Thanks, ``pip install sk-video`` works too and I will use that going forward for consistency. My first test was good. No time change and no segFault. That video was only 11 seconds though. I will continue testing with my other videos from before.

**Comment by SleepingFox88** [comment]
This issue seems fixed. I re-tested with the two 4k videos from before which had the most problems and the timing is flawless now.

![](https://i.imgur.com/y5mgkB3.png)

Sadly the second video had a segFault at frame 5543/5545 but the timing was fine and the video was completely use-able. I am not sure if TQDM stating the error occurred on frame 5543 is completely accurate because other successfully completed videos stop counting two or so frames before completion. So it's possible the segFault happened after all frames were generated. Though I will note that the video outputted from the segFault states it is 1 second less long.

I recommend closing this issue and considering re-opening issue #24. Though it seems #24 happens far less often than it used to.

**Comment by SleepingFox88** [comment]
It should be noted that since the update that fixed this issue, large videos (4k) take significantly longer to start processing. Possibly a couple minutes instead of a few seconds. But once they start, the speed at which frames are interpolated is fine.
