### ISSUE TITLE
关于psnr

### ISSUE THREAD

**Issue by Heroandzhang** [hzwer/arXiv2020-RIFE#230]
你好，在train.py的evaluate函数中分别求了两个psnr值。训练时，两个psnr值是相等的，这正常吗？
train.py（evaluate函数）：
![2](https://user-images.githubusercontent.com/51253044/148935765-49c6ae9e-d582-484c-b381-fd4911a97052.PNG)
psnr值:
![3](https://user-images.githubusercontent.com/51253044/148935772-ec6143f7-ac76-4774-a920-875ca949c103.PNG)

**Comment by hzwer** [comment]
不好意思我把 teacher 的反馈结果覆盖成了 student，已修
https://github.com/hzwer/arXiv2020-RIFE/commit/5b1b69b232f65ad81a55308da8fd8e6b91d7770d

**Comment by Heroandzhang** [comment]
感谢感谢！！！还想请教您一个问题，train.py的evaluate函数119-223行中，j是什么意思？
![4](https://user-images.githubusercontent.com/51253044/149091101-11804de6-c705-4bb2-9843-a7e7201134cf.PNG)

**Comment by hzwer** [comment]
就是在 tensorboard 中可视化一些图片结果
