### ISSUE TITLE
about loss

### ISSUE THREAD

**Issue by Heroandzhang** [hzwer/arXiv2020-RIFE#232]
您好，我使用单卡2080Ti，batch_size=32训练RIFE。现在训练到了260epoch，学习率和loss值的可视化结果如图。想问一下这正常吗？若不正常，据您分析会是什么原因造成的？期待您百忙之中的回复，谢谢！
![2](https://user-images.githubusercontent.com/51253044/149606864-fe3cd43e-15d6-44aa-aac4-bc3e16de2af4.PNG)
![3](https://user-images.githubusercontent.com/51253044/149606865-f9d0067a-f0ab-42e1-995b-52e3b57a5b36.PNG)

**Comment by hzwer** [comment]
你好，看起来 loss 下降并不正常，参考 https://github.com/hzwer/arXiv2020-RIFE/issues/228
也许可以把学习率设置小一点，因为原来 batchsize 64 lr=3e-4，batchsize=32 的话学习率应当减半

**Comment by Heroandzhang** [comment]
感谢，我发现我截图截错了。训练时的结果是这样的，不知道这样对不对？
![4](https://user-images.githubusercontent.com/51253044/149627777-5e985ee2-0675-4cce-9691-4830966e9b5d.PNG)
。
我已经将lr设置为1e-4。

**Comment by hzwer** [comment]
看起来你似乎中断训练后又 load 继续训了；我的代码逻辑里可能缺了这个部分，比如load后step从哪开始之类的。如果你不确定现在是否有问题，可以先跑 50epoch 报一下结果，psnr应该会在35以上。

**Comment by Heroandzhang** [comment]
好的，谢谢您。我用单卡2080Ti，batch_size=32训练RIFE，使用Vimeo90K测试集测试PSNR为30。我现在已经将loss值降到1e-4，将蒸馏 loss 权重降低为0.008，正在训练。除此之外，您还有其他建议吗？

**Comment by hzwer** [comment]
@Heroandzhang 应该只要梯度不爆炸，psnr35+还是很容易得到的。

**Comment by Heroandzhang** [comment]
你好，我用单卡2080Ti，batch_size=32训练RIFE，蒸馏 loss 权重降低为0.008，将学习率下降了一个数量级，在vimeo测试集上psnr还是等于30。
![image](https://user-images.githubusercontent.com/51253044/150681635-45762747-d30c-4b30-95c4-6083d0f489db.png)
请问还有什么需要修改的吗？还是这是因为显卡太少的问题？

**Comment by hzwer** [comment]
@Heroandzhang 我不理解，检查是否可能是数据灌错了之类的 bug？因为我们最近用其它框架复现，即使没调好，psnr35+也是很容易达到的

**Comment by dawei03896** [comment]
请问一下使用的是那一版的pytorch？

**Comment by Heroandzhang** [comment]
不好意思，我现在已经不做这个工作了，所以没法回答
