### ISSUE TITLE
RIFE just won't open !! Unhandled Ul Exception!

### ISSUE THREAD

**Issue by tj92** [hzwer/arXiv2020-RIFE#234]
This is the error that I got :

Unhandled Ul Exception!

Could not load file or assembly 'netstandard, Version-2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' or one of its dependencies. The system cannot find the file specified.

Stack Trace:

at HTAlt.WinForms.HTButton..ctor(

at FlowframForm1.InitializeComponent() at Flowframes.Program.LaunchMainForm() at Flowframes.Program.Main()

The error has been copied to the clipboard. Please inform the developer about this.

**Comment by Tsubajashi** [comment]
This repository does not contain any graphical interface. Looks like flowframes.
You either have an old Windows Version (like Windows 7) or your Windows 10 is not up to date.
What System and Hardware do you use?

**Comment by tj92** [comment]
> This repository does not contain any graphical interface. Looks like flowframes. You either have an old Windows Version (like Windows 7) or your Windows 10 is not up to date. What System and Hardware do you use?

I use Windows 8.1.  intel core i7-4700MQ, Geforce GT 740M, 16GB RAM, 1 TB SSD

I really have a use for this software. Can you please help me with this error?  Yes its Flowframes. How else can I use RIFE?
\

**Comment by Tsubajashi** [comment]
Sorry, the Hardware really isnt strong enough to handle this, and Windows 8.1 isnt supported by Microsoft anymore :/

**Comment by tj92** [comment]
> Sorry, the Hardware really isnt strong enough to handle this, and Windows 8.1 isnt supported by Microsoft anymore :/

How is microsoft support relevant in this issue? total noob here

**Comment by Tsubajashi** [comment]
Because it uses things which are not made for Windows 8.1 in mind, and are not preinstalled *or* cant get installed at all. (I think the first one applies, most likely is about ".net")
