### ISSUE TITLE
RuntimeError: CUDA error: no kernel image is available for execution on the device

### ISSUE THREAD

**Issue by shuri-takashima** [hzwer/arXiv2020-RIFE#235]
I can't solve it.

**versions**
- Python 3.6.7
- cuda 11.1
- pytorch 1.6.0

I'm trying to interplate a video.

`
$ python inference_video.py --video=demo.mp4 --exp=1
`

error
`
Loaded v3.x HD model.
demo.mp4, 1342.0 frames in total, 25.0FPS to 50.0FPS
The audio will be merged after interpolation process
  0%|                                                                                                                                      | 0/1342.0 [00:00<?, ?it/s]Traceback (most recent call last):
  File "inference_video.py", line 205, in <module>
    I1 = torch.from_numpy(np.transpose(lastframe, (2,0,1))).to(device, non_blocking=True).unsqueeze(0).float() / 255.
RuntimeError: CUDA error: no kernel image is available for execution on the device
`

Could you solve it ?

**Comment by shuri-takashima** [comment]
My environment is broken.
so I make  new  environment again. and no error.

**Comment by mfeldt** [comment]
Would still be nice what was broken and how it was fixed - currently I cannot get it to work.
