### ISSUE TITLE
Evaluation with RIFE-2T2R

### ISSUE THREAD

**Issue by jzyustc** [hzwer/arXiv2020-RIFE#239]
Thanks for your great work! I'm reproducing the results of RIFE-2T2R in the arXiv paper , but I'm confused about the model scaling part (2R).

In the arXiv version, you mentioned "We remove the first down-sample layer of IFNet and add a downsample layer before its output to match the origin pipeline", so what means "the first down-sample layer of IFNet"? Does it means the the bilinear sampling or the first conv layer in IFBlocks? And do I need to remove it in all 3 blocks or only in the first block?

**Comment by hzwer** [comment]
https://github.com/hzwer/arXiv2020-RIFE/blob/77884947007bc29e2b95ca3b0be634f54b5c6b50/model/IFNet.py#L24
conv(in_planes, c//2, 3, 2, 1) => conv(in_planes, c//2, 3, 1, 1)
https://github.com/hzwer/arXiv2020-RIFE/blob/77884947007bc29e2b95ca3b0be634f54b5c6b50/model/IFNet.py#L37
nn.ConvTranspose2d(c, 5, 4, 2, 1) => nn.Conv2d(c, 5, 3, 1, 1)

**Comment by jzyustc** [comment]
Thanks for your reply! My problem is well solved.
