### ISSUE TITLE
"inference_video.py" throws a segmentation fault after finishing interpolation

### ISSUE THREAD

**Issue by SleepingFox88** [hzwer/arXiv2020-RIFE#24]
The outputted video file seems to be left finished in a viewable state. So effectively all this does is make inference_video.py terminate ungracefully after it's finished it's task. However this may be indicative of a greater issue.

**Comment by hzwer** [comment]
When will this segfault be triggered?

**Comment by hzwer** [comment]
Merge to https://github.com/hzwer/arXiv2020-RIFE/issues/23

**Comment by SleepingFox88** [comment]
It happens much less often now but I still got a segFault at the end of interpolating a video so we should consider re-opening this issue.

![](https://i.imgur.com/y5mgkB3.png)

**Comment by hzwer** [comment]
I think I have made threads safer and fixed this issue.

**Comment by SleepingFox88** [comment]
@hzwer I'll retest the previously problemed file once #26 is fixed.

**Comment by SleepingFox88** [comment]
Still getting that segFault on the same file

**Comment by SleepingFox88** [comment]
I am no longer getting the segFault I was on the video above with 5543 Frames. That was the one video I was getting sefFaults on. Closing this issue for now.

**Comment by Tetsujinfr** [comment]
I am getting segfault (jetson xavier nx) quite often (but not always) when using inference_video.py --img , although the imges are usually all generated anyway. just ungraceful exit like described here initially.
