### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by SleepingFox88** [hzwer/arXiv2020-RIFE#26]
![](https://i.imgur.com/04chY2W.png)

running ``inference_video.py`` makes the python interpreter eat memory untill system crash. 6 commits ago, it never used more than 1.4GB.

**Comment by SleepingFox88** [comment]
This memory leak was not a problem 6 commits ago 
https://github.com/hzwer/arXiv2020-RIFE/tree/265a8cee5812a23f2ee7ae436d0c6f45be3c63f9

I am not yet sure which specific commit introduced the leak.

**Comment by hzwer** [comment]
Fixed. Caused by buffer.get(timeout=1).
