### ISSUE TITLE
"Sintel_Temple1_1280x544.yuv" of Google Drive HD dataset seems to be missing something

### ISSUE THREAD

**Issue by altair199797** [hzwer/arXiv2020-RIFE#263]
Hello,
in "Sintel_Temple1_1280x544.yuv" it seems that some images are missing. I can't find the other download link unfortunately.
"Sintel_Temple1_1280x544.yuv" is also smaller than the other yuv files of the same resolution.
Thank you in advance!

**Comment by hzwer** [comment]
I calculated the sha1sum of my local video and got 2df580e684e86523d7744fb7a14d326ce9804b3b. The size is 47M.
What does "some images are missing" mean exactly?
I don't know how to confirm this video is correct right now. I'll do some more searching.

**Comment by hzwer** [comment]
I found out that the file's creation date is May 2019, which means I should be providing a video of the original paper.
<img width="1002" alt="image" src="https://user-images.githubusercontent.com/10103856/177824838-d1d95cb6-11a1-496c-b2b8-42c71d5701fa.png">
I noticed that the evaluation used by the author is the first 100 frames, so there may be no impact on the existing evaluation pipeline.
https://github.com/hzwer/ECCV2022-RIFE/blob/f6d90d988d74845a7a77c59ce6ee9b3e33cb412d/benchmark/HD.py#L47
