### ISSUE TITLE
Counting frames takes forever on some videos

### ISSUE THREAD

**Issue by SleepingFox88** [hzwer/arXiv2020-RIFE#27]
Before interpolation, RIFE seems to be running ``ffprobe -v error -count_frames -select_streams v:0 -show_entries stream=nb_read_frames -of default=nokey=1:noprint_wrappers=1 video.mp4`` in order to get the number of frames in the input video. This command is slow on some types of files and can take tens of minutes to complete. Delaying the start of interpolation significantly.

Using ffmpeg, ``ffmpeg -i input.mkv -map 0:v:0 -c copy -f null -`` the counting of frames can be done within seconds instead of minutes. Though the output may take some parsing to isolate the frame count.

A discussion involving both commands:
https://stackoverflow.com/questions/2017843/fetch-frame-count-with-ffmpeg#28376817

**Comment by hzwer** [comment]
```
videoCapture = cv2.VideoCapture(args.video)
fps = videoCapture.get(cv2.CAP_PROP_FPS)
tot_frame = videoCapture.get(cv2.CAP_PROP_FRAME_COUNT)
```
I use these code to get video info, I don't know other efficient ways currently.

**Comment by SleepingFox88** [comment]
So I have been writing a function to get the frame count result from ``ffmpeg -i input.mkv -map 0:v:0 -c copy -f null -``. upon completing this function, I ran a test on 8 video files where I compare the frame count given by my function and your code.

```python
videoCapture = cv2.VideoCapture(args.video)
fps = videoCapture.get(cv2.CAP_PROP_FPS)
tot_frame = videoCapture.get(cv2.CAP_PROP_FRAME_COUNT)
```

2/8 of the videos returned a different frame count that differed by one frame. 

So I ran a third command (that is much slower) to get the frame count of those two videos ``ffprobe -v error -count_frames -select_streams v:0 -show_entries stream=nb_read_frames -of default=nokey=1:noprint_wrappers=1 input.mkv``. It returned the same result as my new function that uses ffmpeg.

It's is looking like this repo's current code for getting the frame count may sometimes yield incorrect results (one too many frames). Do we know any other software I can use to test frame count and further confirm this?

If we are sometimes working with the wrong number of frames, it might explain things like [2 missing frames in output videos](https://github.com/hzwer/arXiv2020-RIFE/issues/28#issuecomment-732259986), and an extremely small (maybe one 29th of a second in a 29FPS video) video-audio desync talked about in #28.

**Comment by SleepingFox88** [comment]
Also, using this repo's current method of getting frame count on my test videos in my test script didn't seem to take more than a couple seconds for any video. This is confusing considering the same code (when used in RIFE) can sometimes take tens of minutes to get the frame count of the same videos.

**Comment by SleepingFox88** [comment]
I have Identified that counting frames via ``tot_frame = getFrameCountUsingFfmpeg(args.video)`` never takes a significant amount of time. Instead the line that is causing significant speed delay is 
```
lastframe = next(videogen)
```

because internally is uses command ``ffprobe -v error -count_frames -select_streams v:0 -show_entries stream=nb_read_frames -of default=nokey=1:noprint_wrappers=1 video.mp4``, which is the slowest known method of getting frame count

before that line, ``videogen`` was assigned as

```
videogen = skvideo.io.vreader(args.video)
```

``skvideo`` is an imported library. So appears skvideo is the problemed software. We either need to find a way instruct it to use the faster method of counting frames or use a different library.

###note

As discussed [above](https://github.com/hzwer/arXiv2020-RIFE/issues/27#issuecomment-734009663), this repo's method for getting total frame count``tot_frame = getFrameCountUsingFfmpeg(args.video)`` and skvideo's command it uses to get total frame count may occasionally differ. This might be a cause of #28

**Comment by hzwer** [comment]
Maybe you can help sk-video to optimize. I think that robust video coding and decoding is a difficult problem. As a showcase of academic research, this project may be difficult to support corner cases.
