### ISSUE TITLE
Not first realtime

### ISSUE THREAD

**Issue by sesse** [hzwer/arXiv2020-RIFE#31]
Hi,

In your paper, you write that “Our proposed RIFE is the first flow-based and real-time VFI algorithm that can process 720p videos at 30FPS.”

I believe this is incorrect; DIS (Dense Inverse Search), a VFI algorithm, was published in 2016 (https://github.com/tikroeger/OF_DIS), is flow-based, and on an RTX 2070 can run stable at 1080p at 60 fps. See https://nageru.sesse.net/ for my GPU implementation (scroll down to Futatabi).

**Comment by hzwer** [comment]
Thanks for pointing it out, we will modify our paper accordingly.

**Comment by sesse** [comment]
It would also be very interesting to see relative quality numbers! I would believe you are quite a bit better than DIS quality-wise, but it would be good to have it measured.

**Comment by sesse** [comment]
I also forgot to ask: I couldn't immediately find out from your paper whether arbitrary t is supported? Ie., if I want to interpolate between two images with t=0.1186, do I need to train the model for that, or can any t be used once trained?

**Comment by hzwer** [comment]
> I also forgot to ask: I couldn't immediately find out from your paper whether arbitrary t is supported? Ie., if I want to interpolate between two images with t=0.1186, do I need to train the model for that, or can any t be used once the initial model is trained?
I think we can feed data with different t to the model and teach it to learn arbitrary interpolation. But Vimeo90K trainning set just includes triplet.

**Comment by sesse** [comment]
OK, so as presented, the model is locked to t=0.5, and any other t needs a new model? Thanks for the information.

**Comment by hzwer** [comment]
> OK, so as presented, the model is locked to t=0.5, and any other t needs a new model? Thanks for the information.

Yes.
