### ISSUE TITLE
Interpolating lead to poor quality and jamming

### ISSUE THREAD

**Issue by BeiluobluesNing** [hzwer/arXiv2020-RIFE#32]
>  https://pan.baidu.com/s/1m72KUBkUApodDDyrGZPhqQ 提取码: kivu 

The 2x and 8x video is jamming in the 0:01..It's hard to say that the video after inserting frames has better MOS, but the speed has really improved a lot.

**Comment by BeiluobluesNing** [comment]
use the windows app to interpolate

**Comment by SleepingFox88** [comment]
@BeiluobluesNing by windows app do you mean ``Flowframes``? 

Also define MOS.

I am having trouble downloading the files from that link for inspection.

**Comment by a1600012888** [comment]
年轻人不讲武德
I think it's a window app issue. I make a new 2X video for you using colab.
链接: https://pan.baidu.com/s/1-WDJMWCNyY_-pTGLEc-IeA 提取码: rp3b 
耗子尾汁

**Comment by a1600012888** [comment]
> @BeiluobluesNing by windows app do you mean `Flowframes`?
> 
> Also define MOS.
> 
> I am not sure what you mean by jamming yet and I am having trouble downloading the files from that link for inspection.

For you to test, https://drive.google.com/file/d/1rOF_Og2N21t5jX8AxiAYAm0T2AJYd-Zg/view?usp=sharing

**Comment by hzwer** [comment]
I think it's a Flowframes issue. Please port this issue to https://github.com/n00mkrad/flowframes.
