### ISSUE TITLE
Not the fastest for multi-frame interpolation

### ISSUE THREAD

**Issue by mrchizx** [hzwer/arXiv2020-RIFE#36]
Hi,

Thanks for open sourcing the code and contributing to the video frame interpolation community. 

In the paper, it mentioned: "Coupled with the large complexity in the bi-directional flow estimation, none of these methods can achieve real-time speed"

I believe that might be inappropriate to say, as the recent published paper (https://www.ecva.net/papers/eccv_2020/papers_ECCV/papers/123720103.pdf) targets efficient multi-frame interpolation. 

It utilizes bi-directional flow estimation as well, but it generates 7 frames for 0.12 second. where your method requires 0.036 * 7 = 0.252 seconds. 

And the model from that paper is compact, which consists of only ~2M parameters, where your fast model has ~10M parameters.

**Comment by hzwer** [comment]
Hello, 
Thanks for your suggestions, but I hope to clarify the following points：
First, my paper explain that mainstream methods use existing optical flow networks, such as PWC-Net, LiteFlowet which cannot achieve 720p real-time speed. 
Second, I want to know where you got the performance data of All at Once paper. Judging from their paper Fig9, I can't get the performance data you reported. We have not claimed any real-time performance other than 2x frame interpolation.
Third, I think that comparing the parameter amount is of little significance in this task. Changing our backbone model to a shuffleNet block can reduce the parameter amount to 10% without loss of performance. We think this should not be a point of contention.

**Comment by mrchizx** [comment]
Hi,

Thanks for the clarification, I understand better on this paper now.

**Comment by linghai06** [comment]
＂Second, we want to know where you got the performance data of "All at Once" paper? According to their paper Fig9, we can't get the performance data you reported. We have not claimed any real-time performance other than 2x frame interpolation.＂

我也觉得好奇，但是对比他github帐号名和all at once文章的作者就知道了，因为他就是all at once的第一作者，哈哈

**Comment by linghai06** [comment]
> all at once也不放代码，实际效果也测不出来呀，哎

可能华为不让开源？

**Comment by YiWeiHuang-stack** [comment]
噢噢，那倒是，和softsplat那个差不多
adobe估计也不让放

**Comment by YiWeiHuang-stack** [comment]
我最近试了好多2020年出的补帧算法，但是感觉都是论文里PSNR，SSIM高，实际效果都和DAIN有点距离。。。
https://github.com/lyh-18/Video-Frame-Interpolation-Collections

**Comment by linghai06** [comment]
> 我最近试了好多2020年出的补帧算法，但是感觉都是论文里PSNR，SSIM高，实际效果都和DAIN有点距离。。。
> https://github.com/lyh-18/Video-Frame-Interpolation-Collections

不知道all at once实际怎么样，感觉能够测的工作里面rife的效果跟DAIN是比较接近的了吧(只考虑x2的情况，x4的时候瑕疵会稍微多一点)

**Comment by YiWeiHuang-stack** [comment]
实拍我不清楚，但是动漫不太行，尤其是高速运动场景，DAIN表现好很多

**Comment by linghai06** [comment]
实拍还是挺好的，主要是比dain快多了

**Comment by YiWeiHuang-stack** [comment]
好像有DAIN的15倍以上吧

**Comment by YiWeiHuang-stack** [comment]
就希望能好好优化下动漫补帧效果了

**Comment by hzwer** [comment]
@YiWeiHuang-stack  @linghai06  
v1.7 大幅优化了动画插帧
