### ISSUE TITLE
CUDA out of memory though there supposed to be enough VRAM

### ISSUE THREAD

**Issue by NAXX2008** [hzwer/arXiv2020-RIFE#43]
> https://github.com/n00mkrad/flowframes/issues/2#issuecomment-737099259

I got below message when running RIFE integrated in [Flowframes](https://github.com/n00mkrad/flowframes).

```
CUDA out of memory. Tried to allocate 60.00 MiB (GPU 0; 6.00 GiB total capacity; 348.98 MiB already allocated; 8.99 MiB free; 444.00 MiB reserved in total by PyTorch)
```

Full stack is as below. No other VRAM-sensitive apps were running at the meanwhile.

```
12-2-2020 16:29:30: [E] Traceback (most recent call last):
12-2-2020 16:29:30: [E]   File "interp-parallel.py", line 138, in <module>
12-2-2020 16:29:30: [E]     inferences = make_inference(model, I0, I1, exp=args.times)
12-2-2020 16:29:30: [E]   File "interp-parallel.py", line 110, in make_inference
12-2-2020 16:29:30: [E]     middle = model.inference(I0, I1)
12-2-2020 16:29:30: [E]   File "D:\Apps\Flowframes\FlowframesData\pkgs\rife-cuda\model\RIFE.py", line 207, in inference
12-2-2020 16:29:30: [E]     return self.predict(imgs, flow, training=False).detach()
12-2-2020 16:29:30: [E]   File "D:\Apps\Flowframes\FlowframesData\pkgs\rife-cuda\model\RIFE.py", line 191, in predict
12-2-2020 16:29:30: [E]     refine_output, warped_img0, warped_img1, warped_img0_gt, warped_img1_gt = self.fusionnet(
12-2-2020 16:29:30: [E]   File "D:\Apps\Flowframes\FlowframesData\pkgs\py\Lib\site-packages\torch\nn\modules\module.py", line 722, in _call_impl
12-2-2020 16:29:30: [E]     result = self.forward(*input, **kwargs)
12-2-2020 16:29:30: [E]   File "D:\Apps\Flowframes\FlowframesData\pkgs\rife-cuda\model\RIFE.py", line 118, in forward
12-2-2020 16:29:30: [E]     x = self.up3(torch.cat((x, s0), 1))
12-2-2020 16:29:30: [E]   File "D:\Apps\Flowframes\FlowframesData\pkgs\py\Lib\site-packages\torch\nn\modules\module.py", line 722, in _call_impl
12-2-2020 16:29:30: [E]     result = self.forward(*input, **kwargs)
12-2-2020 16:29:30: [E]   File "D:\Apps\Flowframes\FlowframesData\pkgs\py\Lib\site-packages\torch\nn\modules\container.py", line 117, in forward
12-2-2020 16:29:30: [E]     input = module(input)
12-2-2020 16:29:30: [E]   File "D:\Apps\Flowframes\FlowframesData\pkgs\py\Lib\site-packages\torch\nn\modules\module.py", line 722, in _call_impl
12-2-2020 16:29:30: [E]     result = self.forward(*input, **kwargs)
12-2-2020 16:29:30: [E]   File "D:\Apps\Flowframes\FlowframesData\pkgs\py\Lib\site-packages\torch\nn\modules\conv.py", line 905, in forward
12-2-2020 16:29:30: [E]     return F.conv_transpose2d(
12-2-2020 16:29:30: [E] RuntimeError: CUDA out of memory. Tried to allocate 60.00 MiB (GPU 0; 6.00 GiB total capacity; 348.98 MiB already allocated; 8.99 MiB free; 444.00 MiB reserved in total by PyTorch)
```

**Comment by NAXX2008** [comment]
BTW, one piece of video in 20FPS triggerred this problem but another one in 25FPS didn't. They are both 720p and encoded by x265, file size about 20MB.

**Comment by hzwer** [comment]
Hi, I think we should fall back to the non-parallel version, because single-card parallel is slower on most devices. If you can upload the video to google drive for me to download, I can check the error.

**Comment by hzwer** [comment]
In other words, we think that continuing to maintain a single-card parallel version is likely to introduce new problems, so please re-integrate inference_video.py.

**Comment by NAXX2008** [comment]
Got it. You can close this issue as won't fix. Thanks.

**Comment by hzwer** [comment]
> Got it. You can close this issue if won't fix. Thanks.

From your log, CUDA OOM is seems not a bug. I think inference_video will not cause it.

**Comment by n00mkrad** [comment]
> Hi, I think we should fall back to the non-parallel version, because single-card parallel is slower on most devices. And the parallel version significantly increases the memory overhead. If you can upload the video to google drive for me to download, I can check the error.

Hmmm, on my RTX 2070S, the parallel code is noticably faster.
The non-parallel code only reaches about 75-80% GPU utilization.

**Comment by hzwer** [comment]
> > Hi, I think we should fall back to the non-parallel version, because single-card parallel is slower on most devices. And the parallel version significantly increases the memory overhead. If you can upload the video to google drive for me to download, I can check the error.
> 
> Hmmm, on my RTX 2070S, the parallel code is noticably faster.
> The non-parallel code only reaches about 75-80% GPU utilization.

OK. I will add a flag to support that.
