### ISSUE TITLE
Could RIFE solve the gap between different parts?

### ISSUE THREAD

**Issue by edmund-zhao** [hzwer/arXiv2020-RIFE#44]
For my perspectives, Dain will output some ugly frames.
[itch](https://itch.io/t/1020954/help-the-ugly-interpolated-frames)

**Comment by hzwer** [comment]
I will make a simple check, which can filter most transitions. https://github.com/hzwer/arXiv2020-RIFE/blob/d1eb884a24dd2f7cfd3377738b976364b29f5dda/inference_video.py#L138

**Comment by edmund-zhao** [comment]
Can we use SSIM to identify the various transformations by compared with per frame? 
Thx for your help
