### ISSUE TITLE
8x Interpolation Support for inference_video.py

### ISSUE THREAD

**Issue by n00mkrad** [hzwer/arXiv2020-RIFE#47]
Hello,

is it possible to enable 8x (exp 3) interpolation for video inference?

**Comment by hzwer** [comment]
Now we support any exp interpolation.

**Comment by StoneCypher** [comment]
Does any exp mean any power of two, by repetition, or can I just pick an arbitrary number?

Like, could I do thirds if I wanted to, or would I be better off going up to 16x then dropping 13 frames throughout?

**Comment by hzwer** [comment]
The current model only supports synthetic intermediate frames. If you set exp=4, you will get 1 + 2 + 4 + 8 = 15 intermediate frames. Other multiples interpolation can only be achieved by dropping some results.
