### ISSUE TITLE
Cannot load model properly

### ISSUE THREAD

**Issue by rastaman7** [hzwer/arXiv2020-RIFE#48]
Hello,
When I run 
python inference_img.py --img demo/I0_0.png demo/I0_1.png --exp=4

I get this error

Traceback (most recent call last):
  File "inference_img.py", line 18, in <module>
    model.load_model('./train_log', -1)
  File "/workspace/interpolation/RIFE/model/RIFE_HD.py", line 179, in load_model
    convert(torch.load('{}/flownet.pkl'.format(path), map_location=device)))
  File "/opt/conda/envs/RIFE/lib/python3.6/site-packages/torch/nn/modules/module.py", line 1052, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for IFNet:
	Missing key(s) in state_dict: "block3.conv0.0.weight", "block3.conv0.1.weight", "block3.conv0.1.bias", "block3.conv0.1.running_mean", "block3.conv0.1.running_var", "block3.conv0.2.weight",
...

Could you please tell me how to fix this?
(I followed the instructions on the github page and the youtube video)

**Comment by hzwer** [comment]
Hello，it seems that you download old models. Make sure the zip name iscontains “HD”.

**Comment by hzwer** [comment]
https://drive.google.com/file/d/11l8zknO1V5hapv2-Ke4DG9mHyBomS0Fc/view?usp=sharing

**Comment by rastaman7** [comment]
Thank you very much for the response.
Yes, I was using a different model(RIFE_trained_model_new), but now it works.
Thank you!
