### ISSUE TITLE
关于flow_gt于loss_dis

### ISSUE THREAD

**Issue by xxh96** [hzwer/arXiv2020-RIFE#49]
作者您好，我有点疑问。
在loss代码中，根据权重， loss_cons应该是论文中的loss_dis吧？
for i in range(3):
            loss_cons += self.epe(flow_list[i], flow_gt[:, :2], 1)
            loss_cons += self.epe(-flow_list[i], flow_gt[:, 2:4], 1)
![image](https://user-images.githubusercontent.com/36263119/101143075-62a28100-3651-11eb-9b4f-305adf943783.png)
定义是这样的，flow_list[i]于-flow_list[i]是代表0->1和1->0？
论文中的是0->t，和t->1？

**Comment by hzwer** [comment]
flow_list[I] 是0->t 和t->1

**Comment by hzwer** [comment]
在我们的 paper 中，没有使用取负号来实现光流逆转，取负号是来自于论文第三页 公式 (1)
