### ISSUE TITLE
What does --fps do?

### ISSUE THREAD

**Issue by StoneCypher** [hzwer/arXiv2020-RIFE#5]
In your colab example, you upsample a 25 fps video by 2x, which seems like it ought to produce 50fps, but then you encode it with --fps 60, and the output is in fact 60fps

does that mean every fifth frame is being repeated? or is it not actually 2x but rather some fraction above 2x

**Comment by hzwer** [comment]
This parameter is used to control the number of frames played per second of the output video. I will adjust the colab code.

**Comment by AlexanderKozhevin** [comment]
@hzwer I applied --fps 60 and my video became from 5 minutes long to 8 minutes long :(

```
!nvidia-smi
!python3 inference_video.py --exp=2 --video=/content/input.mp4 --fps=60 
```

**Comment by hzwer** [comment]
> @hzwer I applied --fps 60 and my video became from 5 minutes long to 8 minutes long :(
> 
> ```
> !nvidia-smi
> !python3 inference_video.py --exp=2 --video=/content/input.mp4 --fps=60 
> ```
> 
> Same with exp=1

If you don't want to change the duration of your video, please do not set --fps.
