### ISSUE TITLE
怎样能补出DAIN那种特殊的丝滑感

### ISSUE THREAD

**Issue by YiWeiHuang-stack** [hzwer/arXiv2020-RIFE#50]
同样的视频补4倍帧率，为什么感觉DAIN更丝滑一些
DAIN:    https://drive.google.com/file/d/1_P4GmHiurc31pNenIMkfw2jd3LDn_7-L/view?usp=sharing
RIFE:     https://drive.google.com/file/d/1MoUG4wfidarmuYIKlhbq4pFbsHSZNEHx/view?usp=sharing

**Comment by hzwer** [comment]
我进行了逐帧对比，发现 RIFE 每四帧会出现一个反常的间隔，因此视觉感受和 DAIN 产生差距
求问你的这两段视频分别是如何生成的，以及能不能给我一下原视频？

**Comment by YiWeiHuang-stack** [comment]
https://drive.google.com/file/d/1GO46Zma6QPA2mr6WHDizKpKwOQOzzX-r/view?usp=sharing

**Comment by YiWeiHuang-stack** [comment]
使用的应该是v1.4的模型

**Comment by hzwer** [comment]
赞！我测试了一下，1.5 版确实解决了这个问题。flowframe 可能过几天也会同步更新的。

**Comment by YiWeiHuang-stack** [comment]
赞！(≧∇≦)ﾉ  我马上下载新的模型试试其他素材

**Comment by YiWeiHuang-stack** [comment]
https://www.youtube.com/watch?v=x67aYuZ-0YI
这里从38秒开始到44秒两个片段，感觉DAIN补的太好了，RIFE能补出类似的效果么

**Comment by hzwer** [comment]
> https://www.youtube.com/watch?v=x67aYuZ-0YI
> 这里从38秒开始到44秒两个片段，感觉DAIN补的太好了，RIFE能补出类似的效果么

这个我也不知道呀

**Comment by YiWeiHuang-stack** [comment]
我自己用DAIN-APP是补不出来这个效果，所以我怀疑他抽帧了
我用类似的办法抽帧用RIFE补足，但是发现画面质量有点低
https://drive.google.com/file/d/1HG1w18cdFmb2QBcZcv_Yq-DMlQg6lc-6/view?usp=sharing

**Comment by hzwer** [comment]
据说 DAIN 有个 animation 版，但我还不太了解他是怎么做的。我们目前动画效果还没有优化的很好。
