### ISSUE TITLE
There's a problem

### ISSUE THREAD

**Issue by So-Yp** [hzwer/arXiv2020-RIFE#51]
这里执行程序总是提示这个https://drive.google.com/file/d/19wbvu4B0Td9y_mS-ECaWaApQ-Nwi4e6o/view?usp=sharing
在本地笔记本没有问题，有哪里需要修改的吗？？

**Comment by hzwer** [comment]
Hi, 重新 git pull 一下，我把这行删掉了。
原因是 pytorch >= 1.0 才有的这个接口，我忘记改了。

**Comment by So-Yp** [comment]
谢谢，我尝试下

**Comment by So-Yp** [comment]
hi，补帧前后色彩有点差异 https://drive.google.com/file/d/1pm5gIVYYJthAHerwrS2IkHcK9j-00m8a/view?usp=sharing
，这个怎么设置色彩和视频画质的高清
python inference_H264video.py --exp=2 --video=xxx.MP4

**Comment by hzwer** [comment]
> hi，补帧前后色彩有点差异 https://drive.google.com/file/d/1pm5gIVYYJthAHerwrS2IkHcK9j-00m8a/view?usp=sharing
> ，这个怎么设置色彩和视频画质的高清
> python inference_H264video.py --exp=2 --video=xxx.MP4

这种情况可能可以
1.  把 RIFE 加上 --png 输出图片，看看有没有色彩变化
2. 用 ffmpeg 把视频处理成图片，RIFE在图片上处理，再压成视频
我不确定是哪一步造成了色彩变化

**Comment by So-Yp** [comment]
hi，试了第一步，--png输出图片还是有色差，所以我用ffmpeg 把视频处理成图片，
RIFE如何批量补帧并压成视频呢？或是对系列照片X2，X4补帧，然后用ffmpeg 把图片处理成视频？

**Comment by hzwer** [comment]
有个 --img=input/，这样会接受图片作为输入，默认输出是视频

**Comment by So-Yp** [comment]
python3 inference_video.py --exp=2 --img=input/
并没有看到输出的视频文件？？

**Comment by hzwer** [comment]
现在的接口只针对输入是 数字.png 这种名字的图片

**Comment by So-Yp** [comment]
最后压制的视频可以自定义编码与码率？参数吗？

**Comment by So-Yp** [comment]
编码出现了问题 https://drive.google.com/file/d/1W0fdNsyB_bccTbEsPAzMA7tk8kSIlPzQ/view?usp=sharing

**Comment by hzwer** [comment]
这个看起来是合成音频的时候出现了问题，我想办法修一下
各种编码定制化的需求，目前只能转出 png 以后用 ffmpeg 来处理

**Comment by So-Yp** [comment]
hi，如何才能解决这个错误呢？目前opencv和ffmpeg都有安装，lib264不知道怎么在OpenCV: FFMPEG下生效。
OpenCV: FFMPEG: tag 0x34363278/'x264' is not supported with codec id 27 and format 'mp4 / MP4 (MPEG-4 Part 14)'
OpenCV: FFMPEG: fallback to use tag 0x31637661/'avc1'
Could not find encoder for codec id 27: Encoder not found
