### ISSUE TITLE
Don't know what's wrong! :/ 

### ISSUE THREAD

**Issue by kunwar-aditya** [hzwer/arXiv2020-RIFE#53]
So I followed all the defined steps.

1. Git cloned the repo locally
2. Downloaded all the requirements
3. Created a folder inside repo called train_log and moved all the extracted *.pkl files inside
3. Try to apply frame interpolation on a video like python3 inference_video.py --exp=1 --video=video.mp4 

I get this error:
```
Traceback (most recent call last):
  File "inference_video.py", line 81, in <module>
    lastframe = next(videogen)
  File "/Users/kabhinavaditya/.pyenv/versions/3.8.5/lib/python3.8/site-packages/skvideo/io/io.py", line 240, in vreader
    assert _HAS_FFMPEG, "Cannot find installation of ffmpeg."
AssertionError: Cannot find installation of ffmpeg.
```

Could you please help me?

**Comment by TheHardew** [comment]
You have to install ffmpeg. http://ffmpeg.org/download.html

**Comment by So-Yp** [comment]
OpenCV：ffmpeg is not support  h264？
Unknown encoder 'lib264'？
How do opencv, ffmpeg and lib264 work together?

**Comment by kunwar-aditya** [comment]
@TheHardew Nope, I am on Mac!

**Comment by TheHardew** [comment]
@kunwar-aditya I'm not really familiar with mac os, but this seems to be an up to date example of adding things to PATH there: https://medium.com/@grantbrits/editing-path-variable-in-catalina-mac-osx-5532ba447af9
That's also how you could do it on linux using zsh shell, so I think it should work.
Also, you might want to look into [homebrew](https://brew.sh/), it is a package manager and it would allow you to install ffmpeg like this: `brew install ffmpeg`

@So-Yp did you edit the python files used for interpolating video to switch to a different encoder? ffmpeg uses `libx264` (notice the x in between). I'm not sure what's the problem with opencv though.

**Comment by So-Yp** [comment]
@TheHardew  Yes, I tried to edit the H264 encoding of the python file, but the code reported an error
OpenCV: FFMPEG: tag 0x34363278/'x264' is not supported with codec id 27 and format 'mp4 / MP4 (MPEG-4 Part 14)'
OpenCV: FFMPEG: fallback to use tag 0x31637661/'avc1'

**Comment by TheHardew** [comment]
@So-Yp change line 82 `fourcc = cv2.VideoWriter_fourcc('m', 'p', '4', 'v')` to `fourcc = cv2.VideoWriter_fourcc('h', '2', '6', '4')` and when executing the script add `--ext=mkv`. This seems to work for me (I hope I didn't forget any steps). If you really need mp4 you can after that execute `ffmpeg -i a.mkv -map 0 -c copy a.mp4`. I'm not yet sure, how to change encoding settings. By the way, you should open a new issue for that, so we don't spam here.

**Comment by So-Yp** [comment]
@TheHardew  ok，thanks
