### ISSUE TITLE
Better hosting for the models.

### ISSUE THREAD

**Issue by TheHardew** [hzwer/arXiv2020-RIFE#54]
Would it be possible to provide better hosting for the models?  
Currently, automating the downloads when a new version comes out is hard, even if technically possible.  
I think you could use the git lfs feature for that, it gives 1 GB of storage and 1 GB of bandwith a month, altough maybe there are more suitable options.

**Comment by n00mkrad** [comment]
Maybe the inference script could automatically download the latest model using gdown.

**Comment by TheHardew** [comment]
Last time I tried, `gdown` hasn't worked for me. `rclone` works great, and so I said it is technically possible, but it is still not ideal.

**Comment by hzwer** [comment]
git-lfs is a good choice, but I don’t think it will be much more convenient than google drive, especially for those who are not familiar with lfs, I will keep updating the model version on google drive.

**Comment by TheHardew** [comment]
Sure, as you wish. I'm closing this issue then.
