### ISSUE TITLE
Better version declarations.

### ISSUE THREAD

**Issue by TheHardew** [hzwer/arXiv2020-RIFE#55]
It would be good to provide the version number in some better way, e.g. commit tags. Currently, if I wanted to make a script to package RIFE automatically , I'd have to parse the first line of `README.md` for the version, but of course there's a big chance it will break in the future. There might be also better ways to do it than the tags, I don't use git often, I just found it after quick searching.

**Comment by n00mkrad** [comment]
It might be easier to manually package it instead of cloning the repo and hoping that nothing breaks.
Alternatively, you could fork it.

**Comment by TheHardew** [comment]
I've written a simple PGKBUILD (bascially a bash script) for arch linux (I don't think I'm going to publish it though, I don't want the responsibilty of maintaining it), which packages RIFE from this repo already. The versioning and the models are the only problems. I could resolve them with `rclone` and maybe parsing #41 now that I think about it, but surely I'm not the only one, who would benefit from those changes, so I though about bringing those issues up.

**Comment by hzwer** [comment]
There should be no major changes in the future. At present, the infrastructure has been basically completed, and generally only the model structure or parameters will be changed.

**Comment by TheHardew** [comment]
I think you could still use tags for updating the version, every time you update the model you post a comment in #41 and also update `README.md`, so you could attach the version number to the commit. It's your choice, so I'll not close this issue just yet, feel free to close it or I can do it, after hearing your decision.

Also, thank you for a quick reply, at least I'll be able to start implementing the workarounds quickly.

**Comment by hzwer** [comment]
Nice, I'll keep updating #41.
