### ISSUE TITLE
内存需求怎么计算

### ISSUE THREAD

**Issue by Archieeeeee** [hzwer/arXiv2020-RIFE#56]
首先感谢项目。
问题是：只有CPU没有GPU的机器，32g内存跑1080p视频8X，日志显示"Killed"退出，怀疑是内存不够。想要跑4K视频8X需要多少内存?

**Comment by hzwer** [comment]
有个简单的办法，把
改一下这两个 500，调成 100 看一下能不能 work
https://github.com/hzwer/arXiv2020-RIFE/blob/21a6c26005abd8875c08f3a01c171483e4c89b1c/inference_video.py#L146-147
