### ISSUE TITLE
Flicker on non moving objects

### ISSUE THREAD

**Issue by SleepingFox88** [hzwer/arXiv2020-RIFE#61]
Non moving objects such as HUD in video games seems to flicker or become distorted every few interpolated frames. I personally stated noticing this after using v1.5 and this appears to be visible in the v1.5 model update log case results. Notice the HUD at the bottom of the TF2 image:
https://github.com/hzwer/arXiv2020-RIFE/issues/41#issuecomment-737651979

**Comment by hzwer** [comment]
It will be optimized within a week or two.

**Comment by hzwer** [comment]
Fix on v1.6.
