### ISSUE TITLE
Pre-trained LiteFlowNet model

### ISSUE THREAD

**Issue by lhao0301** [hzwer/arXiv2020-RIFE#62]
Thanks for your wonderful work!

As stated in `training strategy: A LiteFlowNet [14] pre-trained on the FlyingChairs [9] dataset is used as the overpowered teacher in the leakage distillation`, can u release the pre-trained LiteFlowNet model? I can only find the model (released in [LiteFlowNet](https://github.com/twhui/LiteFlowNet)) trained on FlayingChairs+FlayingThings.

**Comment by hzwer** [comment]
Hello, I used the default model from https://github.com/sniklaus/pytorch-liteflownet.
I reviewed the description again, and it seems that this model is trained under FlayingChairs+FlayingThings. This is my mistake, and I will change this description in a future version of the paper.
