### ISSUE TITLE
关于时刻t插帧

### ISSUE THREAD

**Issue by ZhanningGao** [hzwer/arXiv2020-RIFE#63]
paper中IFNet虽然可以估计F_t->0的光流，但是t似乎只能是0.5，或者说取决于训练数据？Fig3似乎是有问题的，I0和I1输入后怎么知道输出的是F_t->0呢，t都没有作为参数输入网络

**Comment by hzwer** [comment]
所以现在只能是固定一个 t，我觉得理论上有数据应该是能够泛化的，因此就没有写死 t=0.5
