### ISSUE TITLE
Add installation for Windows

### ISSUE THREAD

**Issue by Anafeyka** [hzwer/arXiv2020-RIFE#67]
Add installation for Windows to the description This repository works perfectly on this instruction
```
git clone git@github.com:hzwer/arXiv2020-RIFE.git
cd arXiv2020-RIFE

1 pip install torch===1.7.1 torchvision===0.8.2 torchaudio===0.7.2 -f https://download.pytorch.org/whl/torch_stable.html
2 pip install -r requirements_win10.txt
```
**numpy-1.19.4 has error "module not found error: no module named "cv2" on Win, so replaced with numpy-1.19.2**

Easiest way! Anaconda gpu
```
git clone git@github.com:hzwer/arXiv2020-RIFE.git
cd arXiv2020-RIFE

1 conda install pytorch torchvision torchaudio cudatoolkit=10.2 -c pytorch
2 conda install -c conda-forge ffmpeg
3 pip install -r requirements_win10.txt
```
requirements_Win10.txt
```
numpy==1.19.2
tqdm
sk-video
torch
opencv-python
moviepy
```

**Comment by n00mkrad** [comment]
My GUI also has some instructions for using your own Python installation:

https://github.com/n00mkrad/flowframes/blob/main/PythonDependencies.md

**Comment by kankj** [comment]
I use this environment for train.py, and I got a **No rendezvous handler for env://** in line 145 `torch.distributed.init_process_group(backend="nccl", world_size=args.world_size)`
