### ISSUE TITLE
Image Interpolation Requires more GPU memory

### ISSUE THREAD

**Issue by Anafeyka** [hzwer/arXiv2020-RIFE#70]
If I run inference_video.py 1080p on a 6GB GPU everything is fine.

If I run inference_img.py then a typical GPU memory error occurs.
img0 and img1-1080p.

on 3090-2080ti-1080ti-TitanV
is not error.

**Comment by hzwer** [comment]
Fixed. Please git pull and check it.

**Comment by Anafeyka** [comment]
Thanks! I thought I should turn off the gradient calculation!
