### ISSUE TITLE
怎样才能调用NVdia的显卡运行？

### ISSUE THREAD

**Issue by csncxf** [hzwer/arXiv2020-RIFE#77]
hello，hzwer你好，我的配置是1050ti4G i57300HQ 内存16G。按照usage run 的第一个案例输入指令运行的时候CPU占用100了，内存占用也很高。但是显存占用接近零。要怎样才能调动显卡运行呢？

**Comment by hzwer** [comment]
在 python 命令行中试一下 print(torch.cuda.is_available())
如果显示 False，按照 pytorch 官网重装 pytorch

**Comment by csncxf** [comment]
> 在 python 命令行中试一下 print(torch.cuda.is_available())
> 一般会显示 False
> 然后按照 pytorch 官网重装 pytorch

谢谢，已经搞定了！
