### ISSUE TITLE
rgb or bgr？

### ISSUE THREAD

**Issue by linghai06** [hzwer/arXiv2020-RIFE#78]
Hi, hzwer, nice work!

最近在尝试复现你的结果。试了一下你提供的100 个samples，发现通过VimeoDataset给训练网络的图片是bgr格式，但是看inference_video.py，提供给pretrained网络的又是rgb格式。所以想了解清楚一点你训练的时候是用bgr还是rgb呢？

**Comment by hzwer** [comment]
这个确实是我的疏忽，建议可以在训练的时候加上 rgb bgr 翻转的增广，就不用考虑这个问题，也不掉点的
理论上我应该要保持训练和验证都是 rgb

**Comment by linghai06** [comment]
好的，感谢！
