### ISSUE TITLE
Random target framerate conversion

### ISSUE THREAD

**Issue by semel1** [hzwer/arXiv2020-RIFE#80]
Is it possible with RIFE algorithm convert framerate to not only binary(2x,4x,8x) numbers but also to random (i.e. 23.576 to 59.94)
similar to https://github.com/baowenbo/DAIN/?
In his implementation you can specify random target FPS , not just 2x,4x,8x.
Such ability is highly demanded this days and could be great addition to your project.
Actually at https://www.bilibili.com/video/BV1K541157te?from=search&seid=5131698847373645765 it shows 24P to 60P conversion results. How to achieve that?

**Comment by hzwer** [comment]
Sorry, RIFE is currently unable to do this function, I am researching new and improved algorithms.
