### ISSUE TITLE
Training speed and memory management

### ISSUE THREAD

**Issue by Aether** [hzwer/arXiv2020-RIFE#81]
thx for your excellent work! :) 
I saw it takes about 15 hours to converge in your paper, and you use 16 CPUs, 4 GPUs and 20G memory for training.
Did you load all the dataset into memory?
 
I tried to open the image while training, and it takes about 1.2hours to finish one epoch with one 2080Ti, batch_size=32. too slow
So I compressed flow label into np.float16, and tried to loading all the Vimeo dataset and labels into memory, but it need about 80G. 
How did you balance training speed with memory using?

**Comment by hzwer** [comment]
你好，我们内部有一套供数据的分布式系统，所以数据不在内存上，如果没有这种技术的话，可能需要一段时间把图读到内存，过一段时间再换一批数据

**Comment by Aether** [comment]
谢谢回复～我了解啦～
