### ISSUE TITLE
The performance of HD models drop a lot on Vimeo dataset

### ISSUE THREAD

**Issue by liuppboy** [hzwer/arXiv2020-RIFE#86]
Hi, thanks for your nice work. I find that the PSNR of HD models drop a lot on the test set of Vimeo, even less than 34dB. Can you explain why? Many thanks.

**Comment by hzwer** [comment]
Hi, that‘s because I use perceptual loss to train HD model for better visual affect. So the Vimeo90K PSNR will be lower than RIFE reported on our arxiv paper.

**Comment by a1600012888** [comment]
There is a tradeoff between psnr and perceptual scores[1], and higher PSNR does not always produce visually more pleasing results.  

[1] The Perception-Distortion Tradeoff

**Comment by liuppboy** [comment]
Thanks for your reply! Do you use VGG as perceptural loss? Do the perceptual loss actually improve the visual affect? Many thanks!

**Comment by hzwer** [comment]
Yes, I use this repo's code and it definately improve the visual affect. https://github.com/Vandermode/ERRNet
