### ISSUE TITLE
Transparent PNG support

### ISSUE THREAD

**Issue by n00mkrad** [hzwer/arXiv2020-RIFE#91]
Seeing that recently EXR support was added, is it possible to support transparency (alpha channel) for PNG input and output (using `--img --png`) for inference_video.py?

This would enable interpolation of transparent GIFs.

**Comment by YiXinChenChen** [comment]
Thank you for your work.
I would like to ask if you have any follow-up work in Transparent PNG support ？
Or  how can the now model be modified to support transparent channels？

**Comment by hzwer** [comment]
Hello, next version will support this. 1~2 weeks.

**Comment by YiXinChenChen** [comment]
Thank you.！！
This problem has been bothering me for a long time, because most of the videos are RGB and there is not enough RGBA sequence for training. Could you please tell me your solution idea?

**Comment by hzwer** [comment]
Make IFnet to predict flow and mask, omit the refine Unet block.

**Comment by YiXinChenChen** [comment]
Thank you very much and look forward to your good news!

**Comment by hzwer** [comment]
v3.2 model should be able to support this feature.

**Comment by YiXinChenChen** [comment]
> v3.2 model should be able to support this feature.
when I use the v3.2 model, but there are some mistake:
![image](https://user-images.githubusercontent.com/19725109/121139746-ae85eb00-c86b-11eb-9a95-184a2eb3094e.png)
It looks like there's a mismatch between the model and the weights

**Comment by hzwer** [comment]
> v3.2 model should be able to support this feature.
> when I use the v3.2 model, but there are some mistake:
> ![image](https://user-images.githubusercontent.com/19725109/121139746-ae85eb00-c86b-11eb-9a95-184a2eb3094e.png)
> It looks like there's a mismatch between the model and the weights

I upload new files, please retry.

**Comment by YiXinChenChen** [comment]
Thank you very much. I would like to ask what are the datasets of V3.2 training, and it seems that V3.2 is not as good as V3.1 in my own images insertion frames.

**Comment by hzwer** [comment]
> Thank you very much. I would like to ask what are the datasets of V3.2 training, and it seems that V3.2 is not as good as V3.1 in my own images insertion frames.

Vimeo90K + ATD
It seems like I should build a new benchmark.

**Comment by hzwer** [comment]
@n00mkrad Do you realize this feature using v3.4 model?

**Comment by n00mkrad** [comment]
No, transparent input frames will get a white background.

**Comment by hzwer** [comment]
Hi @n00mkrad, I modify the code and test v3.5 model. It should be ok.

**Comment by n00mkrad** [comment]
Alpha does not work for me with RIFE 3.5.

`python inference_video.py --img alphaFrames`

![image](https://user-images.githubusercontent.com/61149547/122061666-0635d080-cdef-11eb-831b-79159d5cdc06.png)

**Comment by n00mkrad** [comment]
Wait, is Alpha only possible in inference_img.py?

**Comment by n00mkrad** [comment]
Video support can be enabled as well by adding the IMREAD_UNCHANGED flag in inference_video.py as well.

**Comment by hzwer** [comment]
@n00mkrad I will fix them all tomorrow. I missed something.

**Comment by catscarlet** [comment]
@hzwer Is this working for gif? I tried with [v3.8 model](https://github.com/hzwer/Practical-RIFE#model-list)
`docker run --rm -it --gpus all -v /dev/dri:/dev/dri -v $PWD:/host rife:latest inference_video --exp=3 --video=image.gif --png`
but in the `./vid_out`, the png image files are still white background instead of transparent.
