### ISSUE TITLE
Ugly Frames

### ISSUE THREAD

**Issue by mrmilo1986** [hzwer/arXiv2020-RIFE#92]
first,  RIFE is great, Thx for all Developer.

Some times i get this ugly frames, at the moment i use 1.7, they are between a complet black frame.

is there something planed for this ?

![vlcsnap-2021-01-13-17h58m08s348](https://user-images.githubusercontent.com/77450788/104610607-90cda480-5684-11eb-8bd5-cfdd8524527d.png)
![vlcsnap-2021-01-13-17h58m14s813](https://user-images.githubusercontent.com/77450788/104610624-93c89500-5684-11eb-836c-62774f44177d.png)

**Comment by n00mkrad** [comment]
Lower the scene detection threshold in inference_video.py from 0.15:

`if diff.mean() > 0.15:`

**Comment by mrmilo1986** [comment]
I tried all from 0.1 to 0.4 always the same

**Comment by Tsubajashi** [comment]
Did you use —skip as an argument?

**Comment by Fadexz** [comment]
That looks like a de-dupe artefact
