### ISSUE TITLE
Artifacts on Optical Flow

### ISSUE THREAD

**Issue by lhao0301** [hzwer/arXiv2020-RIFE#97]
During training with my own data, there are `checkboard artifacts` on the optical flow (gt flow are clean and correct).  Have you met this case? (Is this something to do with the pixshuffle-upscale operator?)

Some examples are as follows:

![image](https://user-images.githubusercontent.com/10356897/105962929-5a981800-60bb-11eb-8a98-0f836d05f50c.png)
![image](https://user-images.githubusercontent.com/10356897/105963363-e1e58b80-60bb-11eb-9c91-1238e9027813.png)

**Comment by hzwer** [comment]
Yes, I met this issue. I recommend you to use Pixelshuffle on feature map rather than final optical flow. You can also use nn.TransposeConv2d to upsample.
